//! Write accumulated learnings to agent context files.
//!
//! When `atomic agent explain --save` runs, learnings are written to two places:
//!
//! 1. **Change's unhashed section** — all learnings (repo, code, workflow) for server UI
//! 2. **Agent context file** — only **Repo** and **Workflow** learnings (this module)
//!
//! Code learnings (with file:line references) are NOT written to context files.
//! They're noisy, they drift with edits, and in a large project they'd grow
//! unbounded. Code learnings live in the change's unhashed section where the
//! server can render them with CRDT graph anchoring.
//!
//! The context file is agent-specific:
//!
//! | Agent | Context File |
//! |---|---|
//! | Claude Code | `CLAUDE.md` |
//! | Gemini CLI | `GEMINI.md` |
//! | Codex | `codex.md` |
//! | OpenCode | `opencode.md` |
//! | Unknown/generic | `.atomic/learnings.md` |
//!
//! # Section Format
//!
//! Learnings are written into a fenced section with HTML comment markers so
//! the module can find and update the section on subsequent runs without
//! touching the rest of the file. New items merge into existing headings
//! — no duplicate `### Repo` or `### Workflow` sections.
//!
//! ```markdown
//! ## Agent Learnings
//!
//! <!-- atomic:learnings:start -->
//!
//! ### Repo
//! - Auth module uses JWT with RS256, not HS256
//!
//! ### Workflow
//! - cargo test --lib is faster for auth changes
//!
//! <!-- atomic:learnings:end -->
//! ```
//!
//! # Deduplication
//!
//! Before appending, existing learnings are read and compared by finding text.
//! Duplicate findings are skipped. This means running `explain --save` multiple
//! times on the same session doesn't produce duplicate entries.
//!
//! # Knowledge Flywheel
//!
//! ```text
//! Agent works → learnings generated → saved to CLAUDE.md
//!     ↑                                        │
//!     └── next session reads CLAUDE.md ←───────┘
//!         agent starts smarter
//! ```
//!
//! # Example
//!
//! ```rust
//! use atomic_agent::learnings::{context_file_for_agent, save_learnings_to_context_file};
//! use atomic_agent::transcript::{Learnings, CodeLearning};
//! use std::path::Path;
//!
//! let learnings = Learnings {
//!     repo: vec!["Auth uses RS256".to_string()],
//!     code: vec![CodeLearning::new("src/auth.rs", Some(42), "Wrong timezone")],
//!     workflow: vec!["cargo test --lib is faster".to_string()],
//! };
//!
//! // Determine the context file
//! let file = context_file_for_agent("claude-code");
//! assert_eq!(file, "CLAUDE.md");
//!
//! // Save learnings (appends Repo + Workflow to the file, deduplicates)
//! // Code learnings are excluded — they live in the change's unhashed section.
//! // save_learnings_to_context_file(Path::new("/path/to/repo"), "claude-code", &learnings).unwrap();
//! ```

use std::collections::HashMap;
use std::path::{Path, PathBuf};

use crate::transcript::{CodeLearning, Learnings};

// Constants

/// Start marker for the learnings section in agent context files.
const SECTION_START: &str = "<!-- atomic:learnings:start -->";

/// End marker for the learnings section in agent context files.
const SECTION_END: &str = "<!-- atomic:learnings:end -->";

/// Section heading written above the markers.
const SECTION_HEADING: &str = "## Agent Learnings";

/// Note written below the heading.
const SECTION_NOTE: &str =
    "<!-- Auto-generated by atomic agent explain --save. Do not edit between the markers. -->";

// Context File Resolution

/// Returns the context file name for a given agent.
///
/// Each agent reads a specific markdown file at session start for project
/// context. Learnings are appended to this file so the agent reads them
/// automatically on the next session.
///
/// # Examples
///
/// ```rust
/// use atomic_agent::learnings::context_file_for_agent;
///
/// assert_eq!(context_file_for_agent("claude-code"), "CLAUDE.md");
/// assert_eq!(context_file_for_agent("gemini-cli"), "GEMINI.md");
/// assert_eq!(context_file_for_agent("agy"), "AGENTS.md");
/// assert_eq!(context_file_for_agent("codex"), "codex.md");
/// assert_eq!(context_file_for_agent("opencode"), "opencode.md");
/// assert_eq!(context_file_for_agent("kiro"), "AGENTS.md");
/// assert_eq!(context_file_for_agent("unknown"), ".atomic/learnings.md");
/// ```
pub fn context_file_for_agent(agent_name: &str) -> &'static str {
    match agent_name {
        "claude-code" => "CLAUDE.md",
        "gemini-cli" => "GEMINI.md",
        "agy" => "AGENTS.md",
        "codex" => "codex.md",
        "opencode" => "opencode.md",
        "kiro" => "AGENTS.md",
        _ => ".atomic/learnings.md",
    }
}

/// Returns the full path to the agent's context file in a repository.
pub fn context_file_path(repo_root: &Path, agent_name: &str) -> PathBuf {
    repo_root.join(context_file_for_agent(agent_name))
}

// Format Learnings as Markdown

/// Format learnings as individual list items grouped by category.
///
/// Only includes **Repo** and **Workflow** learnings. Code learnings (with
/// file:line references) are stored in the change's unhashed section, not
/// in the context file — they're noisy, they drift with edits, and in a
/// large project they'd grow unbounded.
///
/// Returns a map of heading → list items so callers can merge into
/// existing headings instead of duplicating them.
///
/// # Example Output
///
/// ```text
/// ### Repo
/// - Auth module uses JWT with RS256, not HS256
///
/// ### Workflow
/// - cargo test --lib is faster for auth changes
/// ```
pub fn format_learnings_markdown(learnings: &Learnings) -> String {
    let mut out = String::new();

    if !learnings.repo.is_empty() {
        out.push_str("### Repo\n");
        for item in &learnings.repo {
            out.push_str(&format!("- {}\n", item));
        }
        out.push('\n');
    }

    // Code learnings are intentionally NOT written to the context file.
    // They live in the change's unhashed section where the server can
    // render them with CRDT graph anchoring. The context file only gets
    // the durable, location-independent knowledge.

    if !learnings.workflow.is_empty() {
        out.push_str("### Workflow\n");
        for item in &learnings.workflow {
            out.push_str(&format!("- {}\n", item));
        }
        out.push('\n');
    }

    out
}

/// Count how many learnings would be written to the context file.
///
/// Only counts Repo and Workflow — Code learnings are excluded.
pub fn context_file_learning_count(learnings: &Learnings) -> usize {
    learnings.repo.len() + learnings.workflow.len()
}

/// Format a single code learning as a markdown list item.
///
/// ```text
/// src/auth/login.rs:42 (validate_token) — Token expiry compared with wrong timezone [bug]
/// ```
#[allow(dead_code)]
fn format_code_learning(learning: &CodeLearning) -> String {
    let mut s = learning.path.clone();

    if let Some(line) = learning.line {
        s.push_str(&format!(":{}", line));
        if let Some(end) = learning.end_line {
            s.push_str(&format!("-{}", end));
        }
    }

    if let Some(ref func) = learning.function {
        s.push_str(&format!(" ({})", func));
    }

    s.push_str(&format!(" — {}", learning.finding));

    if let Some(ref category) = learning.category {
        s.push_str(&format!(" [{}]", category));
    }

    s
}

// Read Existing Learnings

/// Parse the existing learnings section into a map of heading → list items.
///
/// Returns a map like `{"### Repo" => ["- item1", "- item2"], "### Workflow" => ["- tip"]}`.
/// Returns an empty map if no section exists.
fn parse_existing_section(content: &str) -> HashMap<String, Vec<String>> {
    let mut sections: HashMap<String, Vec<String>> = HashMap::new();

    let start_idx = match content.find(SECTION_START) {
        Some(idx) => idx + SECTION_START.len(),
        None => return sections,
    };

    let end_idx = match content[start_idx..].find(SECTION_END) {
        Some(idx) => start_idx + idx,
        None => return sections,
    };

    let section_text = &content[start_idx..end_idx];
    let mut current_heading: Option<String> = None;

    for line in section_text.lines() {
        let trimmed = line.trim();
        if trimmed.starts_with("### ") {
            current_heading = Some(trimmed.to_string());
        } else if trimmed.starts_with("- ") {
            if let Some(ref heading) = current_heading {
                sections
                    .entry(heading.clone())
                    .or_default()
                    .push(trimmed.to_string());
            }
        }
    }

    sections
}

/// Collect all existing learning lines (flat list) for dedup checking.
fn read_existing_learnings(content: &str) -> Vec<String> {
    parse_existing_section(content)
        .into_values()
        .flatten()
        .collect()
}

/// Check if a learning line is already present in the existing learnings.
///
/// Compares by the finding text (after the "— ") to handle cases where
/// the line number changed but the finding is the same.
fn is_duplicate(existing: &[String], new_line: &str) -> bool {
    // Extract the finding part (after "— ") for fuzzy matching
    let new_finding = extract_finding(new_line);

    existing.iter().any(|existing_line| {
        let existing_finding = extract_finding(existing_line);
        // Match on finding text, ignoring location differences
        !new_finding.is_empty() && new_finding == existing_finding
    })
}

/// Extract the finding portion from a learning line.
///
/// Given `"- src/auth.rs:42 — Wrong timezone [bug]"`, returns `"Wrong timezone"`.
/// Given `"- Auth uses RS256"`, returns `"Auth uses RS256"`.
fn extract_finding(line: &str) -> String {
    let stripped = line.strip_prefix("- ").unwrap_or(line);

    // Code learnings have " — " separator
    if let Some(idx) = stripped.find(" — ") {
        let after = &stripped[idx + 4..]; // skip " — "
                                          // Strip category suffix like " [bug]"
        if let Some(bracket) = after.rfind(" [") {
            return after[..bracket].trim().to_string();
        }
        return after.trim().to_string();
    }

    // Repo/workflow learnings are just the text
    stripped.trim().to_string()
}

// Deduplication

/// Remove learnings that already exist in the context file.
///
/// Returns a new `Learnings` with only the Repo and Workflow entries that
/// are not already present. Code learnings are always empty in the result
/// because they're not written to context files.
///
/// Comparison is by finding text (exact match on the list item content).
pub fn dedup_learnings(existing_content: &str, new_learnings: &Learnings) -> Learnings {
    let existing = read_existing_learnings(existing_content);

    let repo: Vec<String> = new_learnings
        .repo
        .iter()
        .filter(|item| !is_duplicate(&existing, &format!("- {}", item)))
        .cloned()
        .collect();

    // Code learnings are not written to context files — skip them
    let code: Vec<CodeLearning> = Vec::new();

    let workflow: Vec<String> = new_learnings
        .workflow
        .iter()
        .filter(|item| !is_duplicate(&existing, &format!("- {}", item)))
        .cloned()
        .collect();

    Learnings {
        repo,
        code,
        workflow,
    }
}

// Save to Context File

/// Save learnings to the agent's context file.
///
/// If the file doesn't exist, creates it with the learnings section.
/// If the file exists but has no learnings section, appends the section.
/// If the file exists with a learnings section, merges new learnings
/// (deduplicating by finding text) and rewrites the section.
///
/// # Arguments
///
/// * `repo_root` — Path to the repository root
/// * `agent_name` — Agent registry key (determines which file to write)
/// * `learnings` — The learnings to save
///
/// # Returns
///
/// The number of new learnings added (after deduplication).
///
/// # Errors
///
/// Returns an error if the file cannot be read or written.
pub fn save_learnings_to_context_file(
    repo_root: &Path,
    agent_name: &str,
    learnings: &Learnings,
) -> Result<SaveResult, std::io::Error> {
    if learnings.is_empty() {
        return Ok(SaveResult {
            file_path: context_file_path(repo_root, agent_name),
            added: 0,
            skipped_duplicates: 0,
        });
    }

    let file_path = context_file_path(repo_root, agent_name);

    // Ensure parent directory exists (for .atomic/learnings.md)
    if let Some(parent) = file_path.parent() {
        std::fs::create_dir_all(parent)?;
    }

    // Read existing content (or empty string if file doesn't exist)
    let existing_content = std::fs::read_to_string(&file_path).unwrap_or_default();

    // Dedup against existing learnings
    let original_count = context_file_learning_count(learnings);
    let deduped = dedup_learnings(&existing_content, learnings);
    let new_count = context_file_learning_count(&deduped);
    let skipped = original_count - new_count;

    if new_count == 0 {
        return Ok(SaveResult {
            file_path,
            added: 0,
            skipped_duplicates: skipped,
        });
    }

    // Format the new learnings as individual items and merge by heading
    let new_items = collect_new_items(&deduped);

    // Build the updated file content
    let updated_content = if existing_content.contains(SECTION_START) {
        // Merge into existing headings (no duplicate ### Repo / ### Workflow)
        merge_items_into_section(&existing_content, &new_items)
    } else if existing_content.is_empty() {
        let new_markdown = format_learnings_markdown(&deduped);
        // New file — create with just the learnings section
        build_new_section(&new_markdown)
    } else {
        // Existing file without a learnings section — append
        let new_markdown = format_learnings_markdown(&deduped);
        let mut content = existing_content.clone();
        if !content.ends_with('\n') {
            content.push('\n');
        }
        content.push('\n');
        content.push_str(&build_new_section(&new_markdown));
        content
    };

    std::fs::write(&file_path, updated_content)?;

    Ok(SaveResult {
        file_path,
        added: new_count,
        skipped_duplicates: skipped,
    })
}

/// Result of saving learnings to a context file.
#[derive(Debug)]
pub struct SaveResult {
    /// Path to the context file that was written.
    pub file_path: PathBuf,
    /// Number of new learnings added.
    pub added: usize,
    /// Number of learnings skipped (already present).
    pub skipped_duplicates: usize,
}

impl SaveResult {
    /// Returns true if any learnings were added.
    pub fn has_changes(&self) -> bool {
        self.added > 0
    }
}

impl std::fmt::Display for SaveResult {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        if self.added > 0 {
            write!(
                f,
                "Added {} learning{} to {}",
                self.added,
                if self.added == 1 { "" } else { "s" },
                self.file_path.display(),
            )?;
            if self.skipped_duplicates > 0 {
                write!(f, " ({} already present)", self.skipped_duplicates)?;
            }
        } else {
            write!(
                f,
                "All {} learning{} already in {}",
                self.skipped_duplicates,
                if self.skipped_duplicates == 1 {
                    ""
                } else {
                    "s"
                },
                self.file_path.display(),
            )?;
        }
        Ok(())
    }
}

// Section Building Helpers

/// Build a complete new learnings section (heading + markers + content).
fn build_new_section(learnings_markdown: &str) -> String {
    let mut section = String::new();
    section.push_str(SECTION_HEADING);
    section.push('\n');
    section.push('\n');
    section.push_str(SECTION_NOTE);
    section.push('\n');
    section.push('\n');
    section.push_str(SECTION_START);
    section.push('\n');
    section.push('\n');
    section.push_str(learnings_markdown);
    section.push_str(SECTION_END);
    section.push('\n');
    section
}

/// Collect new learnings as heading → items map for merging.
fn collect_new_items(learnings: &Learnings) -> HashMap<String, Vec<String>> {
    let mut items: HashMap<String, Vec<String>> = HashMap::new();

    for item in &learnings.repo {
        items
            .entry("### Repo".to_string())
            .or_default()
            .push(format!("- {}", item));
    }

    // Code learnings excluded from context file — they live in change.unhashed

    for item in &learnings.workflow {
        items
            .entry("### Workflow".to_string())
            .or_default()
            .push(format!("- {}", item));
    }

    items
}

/// Merge new items into existing section headings without duplicating headings.
///
/// If `### Repo` already exists in the section, new repo items are appended
/// under the existing heading. If a heading doesn't exist yet, it's created.
fn merge_items_into_section(
    existing_content: &str,
    new_items: &HashMap<String, Vec<String>>,
) -> String {
    let start_idx = match existing_content.find(SECTION_START) {
        Some(idx) => idx + SECTION_START.len(),
        None => return existing_content.to_string(),
    };

    let end_marker_idx = match existing_content[start_idx..].find(SECTION_END) {
        Some(idx) => start_idx + idx,
        None => return existing_content.to_string(),
    };

    let before_section = &existing_content[..start_idx];
    let section_body = &existing_content[start_idx..end_marker_idx];
    let after_section = &existing_content[end_marker_idx..];

    // Parse existing section into heading → items
    let mut sections: Vec<(String, Vec<String>)> = Vec::new();
    let mut current_heading: Option<String> = None;
    let mut current_items: Vec<String> = Vec::new();

    for line in section_body.lines() {
        let trimmed = line.trim();
        if trimmed.starts_with("### ") {
            // Save previous heading if any
            if let Some(heading) = current_heading.take() {
                sections.push((heading, std::mem::take(&mut current_items)));
            }
            current_heading = Some(trimmed.to_string());
        } else if trimmed.starts_with("- ") {
            current_items.push(trimmed.to_string());
        }
    }
    if let Some(heading) = current_heading {
        sections.push((heading, current_items));
    }

    // Merge new items into existing headings or append new headings
    let mut merged_headings: std::collections::HashSet<String> = std::collections::HashSet::new();
    for (heading, items) in sections.iter_mut() {
        if let Some(new) = new_items.get(heading) {
            items.extend(new.iter().cloned());
            merged_headings.insert(heading.clone());
        }
    }

    // Add headings that didn't exist yet
    // Use a stable order: Repo first, then Workflow
    for heading in &["### Repo", "### Workflow"] {
        let heading = heading.to_string();
        if !merged_headings.contains(&heading) {
            if let Some(items) = new_items.get(&heading) {
                sections.push((heading, items.clone()));
            }
        }
    }

    // Rebuild the section
    let mut result = String::new();
    result.push_str(before_section);
    result.push('\n');

    for (heading, items) in &sections {
        result.push_str(heading);
        result.push('\n');
        for item in items {
            result.push_str(item);
            result.push('\n');
        }
        result.push('\n');
    }

    result.push_str(after_section);
    result
}

// Tests

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::HashMap;
    use tempfile::TempDir;

    // context_file_for_agent

    #[test]
    fn test_context_file_claude() {
        assert_eq!(context_file_for_agent("claude-code"), "CLAUDE.md");
    }

    #[test]
    fn test_context_file_gemini() {
        assert_eq!(context_file_for_agent("gemini-cli"), "GEMINI.md");
    }

    #[test]
    fn test_context_file_codex() {
        assert_eq!(context_file_for_agent("codex"), "codex.md");
    }

    #[test]
    fn test_context_file_opencode() {
        assert_eq!(context_file_for_agent("opencode"), "opencode.md");
    }

    #[test]
    fn test_context_file_kiro() {
        assert_eq!(context_file_for_agent("kiro"), "AGENTS.md");
    }

    #[test]
    fn test_context_file_unknown() {
        assert_eq!(context_file_for_agent("unknown"), ".atomic/learnings.md");
        assert_eq!(
            context_file_for_agent("my-custom-agent"),
            ".atomic/learnings.md"
        );
    }

    #[test]
    fn test_context_file_path() {
        let path = context_file_path(Path::new("/repo"), "claude-code");
        assert_eq!(path, PathBuf::from("/repo/CLAUDE.md"));
    }

    // format_learnings_markdown

    #[test]
    fn test_format_empty() {
        let learnings = Learnings::default();
        let md = format_learnings_markdown(&learnings);
        assert!(md.is_empty());
    }

    #[test]
    fn test_format_repo_only() {
        let learnings = Learnings {
            repo: vec!["Auth uses RS256".into()],
            code: vec![],
            workflow: vec![],
        };
        let md = format_learnings_markdown(&learnings);
        assert!(md.contains("### Repo"));
        assert!(md.contains("- Auth uses RS256"));
        assert!(!md.contains("### Code"));
        assert!(!md.contains("### Workflow"));
    }

    #[test]
    fn test_format_code_excluded() {
        let learnings = Learnings {
            repo: vec![],
            code: vec![CodeLearning::new("src/auth.rs", Some(42), "Wrong timezone")
                .with_function("validate_token")
                .with_category("bug")],
            workflow: vec![],
        };
        let md = format_learnings_markdown(&learnings);
        // Code learnings should NOT appear in the context file format
        assert!(!md.contains("### Code"));
        assert!(!md.contains("src/auth.rs"));
        assert!(md.is_empty());
    }

    #[test]
    fn test_format_repo_and_workflow_only() {
        let learnings = Learnings {
            repo: vec!["Pattern A".into()],
            code: vec![CodeLearning::new("f.rs", Some(1), "Finding B")],
            workflow: vec!["Tip C".into()],
        };
        let md = format_learnings_markdown(&learnings);
        assert!(md.contains("### Repo"));
        assert!(!md.contains("### Code")); // excluded from context file
        assert!(md.contains("### Workflow"));
        assert!(md.contains("- Pattern A"));
        assert!(!md.contains("- f.rs:1")); // code learning excluded
        assert!(md.contains("- Tip C"));
    }

    #[test]
    fn test_context_file_learning_count() {
        let learnings = Learnings {
            repo: vec!["a".into(), "b".into()],
            code: vec![CodeLearning::new("f", None, "c")], // not counted
            workflow: vec!["d".into()],
        };
        assert_eq!(context_file_learning_count(&learnings), 3); // 2 repo + 1 workflow
    }

    #[test]
    fn test_format_code_learning_no_line() {
        let learning = CodeLearning::new("lib.rs", None, "General pattern");
        assert_eq!(format_code_learning(&learning), "lib.rs — General pattern");
    }

    #[test]
    fn test_format_code_learning_with_range() {
        let learning = CodeLearning::new("f.rs", Some(10), "Issue").with_end_line(20);
        assert_eq!(format_code_learning(&learning), "f.rs:10-20 — Issue");
    }

    #[test]
    fn test_format_code_learning_full() {
        let learning = CodeLearning::new("f.rs", Some(42), "Bug here")
            .with_function("main")
            .with_category("security");
        assert_eq!(
            format_code_learning(&learning),
            "f.rs:42 (main) — Bug here [security]"
        );
    }

    // extract_finding

    #[test]
    fn test_extract_finding_code_learning() {
        let line = "- src/auth.rs:42 (validate_token) — Wrong timezone [bug]";
        assert_eq!(extract_finding(line), "Wrong timezone");
    }

    #[test]
    fn test_extract_finding_code_no_category() {
        let line = "- src/auth.rs:42 — Wrong timezone";
        assert_eq!(extract_finding(line), "Wrong timezone");
    }

    #[test]
    fn test_extract_finding_repo() {
        let line = "- Auth uses RS256";
        assert_eq!(extract_finding(line), "Auth uses RS256");
    }

    #[test]
    fn test_extract_finding_workflow() {
        let line = "- cargo test --lib is faster";
        assert_eq!(extract_finding(line), "cargo test --lib is faster");
    }

    #[test]
    fn test_extract_finding_no_prefix() {
        let line = "Auth uses RS256";
        assert_eq!(extract_finding(line), "Auth uses RS256");
    }

    // is_duplicate

    #[test]
    fn test_duplicate_exact() {
        let existing = vec!["- Auth uses RS256".into()];
        assert!(is_duplicate(&existing, "- Auth uses RS256"));
    }

    #[test]
    fn test_duplicate_code_same_finding_different_line() {
        let existing = vec!["- src/auth.rs:42 — Wrong timezone [bug]".into()];
        // Same finding, different line number
        assert!(is_duplicate(
            &existing,
            "- src/auth.rs:87 — Wrong timezone [bug]"
        ));
    }

    #[test]
    fn test_not_duplicate() {
        let existing = vec!["- Auth uses RS256".into()];
        assert!(!is_duplicate(&existing, "- Auth uses HS256"));
    }

    #[test]
    fn test_not_duplicate_empty_existing() {
        let existing: Vec<String> = vec![];
        assert!(!is_duplicate(&existing, "- anything"));
    }

    // read_existing_learnings

    #[test]
    fn test_read_no_section() {
        let content = "# My Project\n\nSome content.\n";
        assert!(read_existing_learnings(content).is_empty());
    }

    #[test]
    fn test_read_empty_section() {
        let content = format!("# Project\n\n{}\n\n{}\n", SECTION_START, SECTION_END);
        assert!(read_existing_learnings(&content).is_empty());
    }

    #[test]
    fn test_read_with_learnings() {
        let content = format!(
            "# Project\n\n{}\n\n### Repo\n- Learning A\n- Learning B\n\n{}\n",
            SECTION_START, SECTION_END
        );
        let learnings = read_existing_learnings(&content);
        assert_eq!(learnings.len(), 2);
        assert_eq!(learnings[0], "- Learning A");
        assert_eq!(learnings[1], "- Learning B");
    }

    #[test]
    fn test_read_filters_headings() {
        let content = format!(
            "{}\n### Repo\n- Item\n### Code\n- Code item\n{}",
            SECTION_START, SECTION_END
        );
        let learnings = read_existing_learnings(&content);
        assert_eq!(learnings.len(), 2);
        assert!(learnings.iter().all(|l| l.starts_with("- ")));
    }

    // dedup_learnings

    #[test]
    fn test_dedup_no_existing() {
        let learnings = Learnings {
            repo: vec!["New learning".into()],
            code: vec![],
            workflow: vec![],
        };
        let deduped = dedup_learnings("", &learnings);
        assert_eq!(deduped.repo.len(), 1);
    }

    #[test]
    fn test_dedup_removes_existing() {
        let existing = format!(
            "{}\n### Repo\n- Already here\n{}",
            SECTION_START, SECTION_END
        );
        let learnings = Learnings {
            repo: vec!["Already here".into(), "New one".into()],
            code: vec![],
            workflow: vec![],
        };
        let deduped = dedup_learnings(&existing, &learnings);
        assert_eq!(deduped.repo.len(), 1);
        assert_eq!(deduped.repo[0], "New one");
    }

    #[test]
    fn test_dedup_all_duplicates() {
        let existing = format!("{}\n### Repo\n- A\n- B\n{}", SECTION_START, SECTION_END);
        let learnings = Learnings {
            repo: vec!["A".into(), "B".into()],
            code: vec![],
            workflow: vec![],
        };
        let deduped = dedup_learnings(&existing, &learnings);
        assert!(deduped.is_empty());
    }

    #[test]
    fn test_dedup_code_always_empty() {
        // Code learnings are never written to context files, so dedup
        // always returns empty code vec regardless of input
        let learnings = Learnings {
            repo: vec![],
            code: vec![
                CodeLearning::new("src/new.rs", Some(50), "Finding A"),
                CodeLearning::new("src/lib.rs", Some(1), "Finding B"),
            ],
            workflow: vec![],
        };
        let deduped = dedup_learnings("", &learnings);
        assert!(deduped.code.is_empty());
    }

    // build_new_section

    #[test]
    fn test_build_new_section() {
        let md = "### Repo\n- Learning\n\n";
        let section = build_new_section(md);
        assert!(section.contains(SECTION_HEADING));
        assert!(section.contains(SECTION_NOTE));
        assert!(section.contains(SECTION_START));
        assert!(section.contains("- Learning"));
        assert!(section.contains(SECTION_END));
    }

    // merge_into_existing_section

    #[test]
    fn test_merge_appends_to_existing_heading() {
        let existing = format!(
            "# Project\n\n{}\n\n### Repo\n- Existing\n\n{}\n\nOther content.\n",
            SECTION_START, SECTION_END
        );
        let mut new_items = HashMap::new();
        new_items.insert("### Repo".to_string(), vec!["- New repo item".to_string()]);
        let result = merge_items_into_section(&existing, &new_items);

        assert!(result.contains("- Existing"));
        assert!(result.contains("- New repo item"));
        assert!(result.contains("Other content."));
        // Should have only ONE ### Repo heading
        assert_eq!(result.matches("### Repo").count(), 1);
    }

    #[test]
    fn test_merge_adds_new_heading() {
        let existing = format!(
            "{}\n\n### Repo\n- Existing repo\n\n{}\n",
            SECTION_START, SECTION_END
        );
        let mut new_items = HashMap::new();
        new_items.insert(
            "### Workflow".to_string(),
            vec!["- New workflow tip".to_string()],
        );
        let result = merge_items_into_section(&existing, &new_items);

        assert!(result.contains("### Repo"));
        assert!(result.contains("### Workflow"));
        assert!(result.contains("- Existing repo"));
        assert!(result.contains("- New workflow tip"));
        // Each heading appears only once
        assert_eq!(result.matches("### Repo").count(), 1);
        assert_eq!(result.matches("### Workflow").count(), 1);
    }

    #[test]
    fn test_merge_no_markers() {
        let existing = "# Just a file\n";
        let new_items = HashMap::new();
        let result = merge_items_into_section(existing, &new_items);
        assert_eq!(result, existing);
    }

    #[test]
    fn test_merge_both_existing_and_new() {
        let existing = format!(
            "{}\n\n### Repo\n- Old repo\n\n### Workflow\n- Old workflow\n\n{}\n",
            SECTION_START, SECTION_END
        );
        let mut new_items = HashMap::new();
        new_items.insert("### Repo".to_string(), vec!["- New repo".to_string()]);
        new_items.insert(
            "### Workflow".to_string(),
            vec!["- New workflow".to_string()],
        );
        let result = merge_items_into_section(&existing, &new_items);

        // Each heading once
        assert_eq!(result.matches("### Repo").count(), 1);
        assert_eq!(result.matches("### Workflow").count(), 1);
        // All items present
        assert!(result.contains("- Old repo"));
        assert!(result.contains("- New repo"));
        assert!(result.contains("- Old workflow"));
        assert!(result.contains("- New workflow"));
    }

    // save_learnings_to_context_file (filesystem tests)

    #[test]
    fn test_save_new_file() {
        let dir = TempDir::new().unwrap();
        let learnings = Learnings {
            repo: vec!["Pattern A".into()],
            code: vec![CodeLearning::new("f.rs", Some(1), "Finding B")],
            workflow: vec!["Tip C".into()],
        };

        let result = save_learnings_to_context_file(dir.path(), "claude-code", &learnings).unwrap();

        assert_eq!(result.added, 2); // repo + workflow only, code excluded
        assert_eq!(result.skipped_duplicates, 0);
        assert!(result.has_changes());

        // Verify file was created
        let content = std::fs::read_to_string(dir.path().join("CLAUDE.md")).unwrap();
        assert!(content.contains(SECTION_HEADING));
        assert!(content.contains(SECTION_START));
        assert!(content.contains("- Pattern A"));
        assert!(!content.contains("Finding B")); // code learning excluded
        assert!(!content.contains("f.rs")); // code learning excluded
        assert!(content.contains("- Tip C"));
        assert!(content.contains(SECTION_END));
    }

    #[test]
    fn test_save_append_to_existing_file() {
        let dir = TempDir::new().unwrap();
        let claude_md = dir.path().join("CLAUDE.md");

        // Write existing content
        std::fs::write(
            &claude_md,
            "# My Project\n\nExisting project documentation.\n",
        )
        .unwrap();

        let learnings = Learnings {
            repo: vec!["New learning".into()],
            code: vec![],
            workflow: vec![],
        };

        let result = save_learnings_to_context_file(dir.path(), "claude-code", &learnings).unwrap();

        assert_eq!(result.added, 1);

        let content = std::fs::read_to_string(&claude_md).unwrap();
        // Original content preserved
        assert!(content.contains("# My Project"));
        assert!(content.contains("Existing project documentation."));
        // New section appended
        assert!(content.contains(SECTION_HEADING));
        assert!(content.contains("- New learning"));
    }

    #[test]
    fn test_save_merge_into_existing_section() {
        let dir = TempDir::new().unwrap();
        let claude_md = dir.path().join("CLAUDE.md");

        // Write file with existing learnings section
        let existing = format!(
            "# Project\n\n{}\n\n{}\n\n{}\n\n### Repo\n- Existing learning\n\n{}\n",
            SECTION_HEADING, SECTION_NOTE, SECTION_START, SECTION_END
        );
        std::fs::write(&claude_md, &existing).unwrap();

        let learnings = Learnings {
            repo: vec!["New learning".into()],
            code: vec![],
            workflow: vec![],
        };

        let result = save_learnings_to_context_file(dir.path(), "claude-code", &learnings).unwrap();

        assert_eq!(result.added, 1);

        let content = std::fs::read_to_string(&claude_md).unwrap();
        assert!(content.contains("- Existing learning"));
        assert!(content.contains("- New learning"));
        // Should have only ONE ### Repo heading, not two
        assert_eq!(
            content.matches("### Repo").count(),
            1,
            "### Repo should appear exactly once, got:\n{}",
            content
        );
    }

    #[test]
    fn test_save_dedup() {
        let dir = TempDir::new().unwrap();
        let claude_md = dir.path().join("CLAUDE.md");

        // First save
        let learnings = Learnings {
            repo: vec!["Learning A".into(), "Learning B".into()],
            code: vec![],
            workflow: vec![],
        };
        save_learnings_to_context_file(dir.path(), "claude-code", &learnings).unwrap();

        // Second save with overlap
        let learnings2 = Learnings {
            repo: vec![
                "Learning A".into(), // duplicate
                "Learning C".into(), // new
            ],
            code: vec![],
            workflow: vec![],
        };
        let result =
            save_learnings_to_context_file(dir.path(), "claude-code", &learnings2).unwrap();

        assert_eq!(result.added, 1); // only C
        assert_eq!(result.skipped_duplicates, 1); // A was skipped

        let content = std::fs::read_to_string(&claude_md).unwrap();
        // A should appear once, not twice
        assert_eq!(content.matches("Learning A").count(), 1);
        assert!(content.contains("Learning B"));
        assert!(content.contains("Learning C"));
    }

    #[test]
    fn test_save_merge_no_heading_duplication() {
        let dir = TempDir::new().unwrap();
        let claude_md = dir.path().join("CLAUDE.md");

        // First save creates section with Repo
        let learnings1 = Learnings {
            repo: vec!["Learning A".into()],
            code: vec![],
            workflow: vec!["Tip X".into()],
        };
        save_learnings_to_context_file(dir.path(), "claude-code", &learnings1).unwrap();

        // Second save adds more to Repo and Workflow
        let learnings2 = Learnings {
            repo: vec!["Learning B".into()],
            code: vec![],
            workflow: vec!["Tip Y".into()],
        };
        save_learnings_to_context_file(dir.path(), "claude-code", &learnings2).unwrap();

        let content = std::fs::read_to_string(&claude_md).unwrap();

        // Each heading should appear exactly once
        assert_eq!(
            content.matches("### Repo").count(),
            1,
            "### Repo duplicated:\n{}",
            content
        );
        assert_eq!(
            content.matches("### Workflow").count(),
            1,
            "### Workflow duplicated:\n{}",
            content
        );
        // All items present
        assert!(content.contains("- Learning A"));
        assert!(content.contains("- Learning B"));
        assert!(content.contains("- Tip X"));
        assert!(content.contains("- Tip Y"));
    }

    #[test]
    fn test_save_code_learnings_excluded() {
        let dir = TempDir::new().unwrap();

        // Learnings with code — code should NOT appear in the file
        let learnings = Learnings {
            repo: vec!["Repo item".into()],
            code: vec![CodeLearning::new("f.rs", Some(42), "Code finding")],
            workflow: vec![],
        };

        let result = save_learnings_to_context_file(dir.path(), "claude-code", &learnings).unwrap();

        // Only 1 added (the repo item), not 2
        assert_eq!(result.added, 1);

        let content = std::fs::read_to_string(dir.path().join("CLAUDE.md")).unwrap();
        assert!(content.contains("- Repo item"));
        assert!(!content.contains("Code finding"));
        assert!(!content.contains("### Code"));
        assert!(!content.contains("f.rs"));
    }

    #[test]
    fn test_save_empty_learnings() {
        let dir = TempDir::new().unwrap();
        let learnings = Learnings::default();

        let result = save_learnings_to_context_file(dir.path(), "claude-code", &learnings).unwrap();

        assert_eq!(result.added, 0);
        assert!(!result.has_changes());
        // File should not be created
        assert!(!dir.path().join("CLAUDE.md").exists());
    }

    #[test]
    fn test_save_creates_parent_dirs() {
        let dir = TempDir::new().unwrap();
        let learnings = Learnings {
            repo: vec!["test".into()],
            code: vec![],
            workflow: vec![],
        };

        // "unknown" agent writes to .atomic/learnings.md — needs parent dir
        let result =
            save_learnings_to_context_file(dir.path(), "unknown-agent", &learnings).unwrap();

        assert!(result.has_changes());
        assert!(dir.path().join(".atomic/learnings.md").exists());
    }

    #[test]
    fn test_save_gemini() {
        let dir = TempDir::new().unwrap();
        let learnings = Learnings {
            repo: vec!["Gemini learning".into()],
            code: vec![],
            workflow: vec![],
        };

        save_learnings_to_context_file(dir.path(), "gemini-cli", &learnings).unwrap();

        assert!(dir.path().join("GEMINI.md").exists());
        let content = std::fs::read_to_string(dir.path().join("GEMINI.md")).unwrap();
        assert!(content.contains("- Gemini learning"));
    }

    // SaveResult display

    #[test]
    fn test_save_result_display_added() {
        let result = SaveResult {
            file_path: PathBuf::from("CLAUDE.md"),
            added: 3,
            skipped_duplicates: 0,
        };
        let s = result.to_string();
        assert!(s.contains("Added 3 learnings"));
        assert!(s.contains("CLAUDE.md"));
    }

    #[test]
    fn test_save_result_display_added_with_dupes() {
        let result = SaveResult {
            file_path: PathBuf::from("CLAUDE.md"),
            added: 2,
            skipped_duplicates: 1,
        };
        let s = result.to_string();
        assert!(s.contains("Added 2 learnings"));
        assert!(s.contains("1 already present"));
    }

    #[test]
    fn test_save_result_display_all_dupes() {
        let result = SaveResult {
            file_path: PathBuf::from("CLAUDE.md"),
            added: 0,
            skipped_duplicates: 3,
        };
        let s = result.to_string();
        assert!(s.contains("All 3 learnings already in"));
    }

    #[test]
    fn test_save_result_display_singular() {
        let result = SaveResult {
            file_path: PathBuf::from("CLAUDE.md"),
            added: 1,
            skipped_duplicates: 0,
        };
        let s = result.to_string();
        assert!(s.contains("Added 1 learning to")); // singular
        assert!(!s.contains("learnings"));
    }
}
