//! Transcript parsing, reasoning summaries, and unhashed storage.
//!
//! This module handles everything that goes into `change.unhashed["agent_turn"]`:
//!
//! 1. **Condensed transcript** — the raw conversation parsed into structured entries
//! 2. **AI-generated reasoning** — intent, outcome, learnings, friction, open items
//! 3. **Graph anchoring** — CRDT references that keep learnings attached to code as it evolves
//! 4. **Reasoning generation** — `ReasoningGenerator` trait + `ClaudeCliGenerator` implementation
//! 5. **Storage** — attach/extract/strip operations on `Change.unhashed`
//!
//! # Data Flow
//!
//! ```text
//! Agent transcript (JSONL/JSON)
//!     │
//!     ▼
//! condense_transcript()          → Vec<CondensedEntry>
//!     │
//!     ▼
//! format_condensed()             → human-readable text
//!     │
//!     ▼
//! ReasoningGenerator::generate() → TurnReasoning { intent, outcome, learnings, ... }
//!     │
//!     ▼
//! anchor_to_graph()              → CodeLearning._anchor populated from FileOps
//!     │
//!     ▼
//! UnhashedTurnData               → serialized into change.unhashed["agent_turn"]
//! ```
//!
//! # Example
//!
//! ```rust
//! use atomic_agent::transcript::{
//!     CondensedEntry, EntryType, TurnReasoning, Learnings, CodeLearning,
//!     UnhashedTurnData, ToolUseSummary,
//! };
//!
//! // Build condensed transcript entries
//! let entries = vec![
//!     CondensedEntry::user("Fix the auth bug in login.rs"),
//!     CondensedEntry::assistant("I'll fix the token validation..."),
//!     CondensedEntry::tool("Edit", Some("src/auth/login.rs")),
//!     CondensedEntry::tool("Bash", Some("cargo test")),
//!     CondensedEntry::assistant("The fix is applied and tests pass."),
//! ];
//!
//! // Build reasoning (normally generated by LLM)
//! let reasoning = TurnReasoning {
//!     intent: "Fix authentication bug preventing user login".into(),
//!     outcome: "Fixed token validation, all tests passing".into(),
//!     learnings: Learnings {
//!         repo: vec!["Auth module uses JWT with RS256, not HS256".into()],
//!         code: vec![CodeLearning::new(
//!             "src/auth/login.rs",
//!             Some(42),
//!             "Token expiry compared with wrong timezone",
//!         )],
//!         workflow: vec!["cargo test --lib is faster for auth changes".into()],
//!     },
//!     friction: vec!["3 layers of middleware to find the validation".into()],
//!     open_items: vec!["Refresh endpoint has the same bug".into()],
//! };
//!
//! // Package into unhashed turn data
//! let data = UnhashedTurnData {
//!     session_id: "sess-123".into(),
//!     turn_number: 3,
//!     transcript_format: "jsonl".into(),
//!     condensed_transcript: entries,
//!     condensed_text: "...".into(),
//!     prompts: vec!["Fix the auth bug in login.rs".into()],
//!     tools_used: vec![
//!         ToolUseSummary::new("Edit", 1, vec!["src/auth/login.rs".into()]),
//!     ],
//!     reasoning: Some(reasoning),
//!     redacted: false,
//! };
//!
//! assert_eq!(data.turn_number, 3);
//! assert!(data.reasoning.is_some());
//! ```

use std::collections::HashMap;
use std::fmt;
use std::io::Write;
use std::path::PathBuf;
use std::process::Command;

use serde::{Deserialize, Serialize};

use crate::error::{AgentError, AgentResult};

// Condensed Transcript

/// The type of a transcript entry.
#[derive(Clone, Debug, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum EntryType {
    /// A user prompt.
    User,
    /// An assistant (model) response.
    Assistant,
    /// A tool invocation.
    Tool,
}

impl fmt::Display for EntryType {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            EntryType::User => write!(f, "User"),
            EntryType::Assistant => write!(f, "Assistant"),
            EntryType::Tool => write!(f, "Tool"),
        }
    }
}

/// A single entry in the condensed transcript.
///
/// The raw JSONL/JSON transcript from the agent is parsed into these
/// structured entries, filtering out noise (file contents from Read tools,
/// verbose bash output, skill injections).
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct CondensedEntry {
    /// The type of entry.
    pub entry_type: EntryType,

    /// Text content for user/assistant entries.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub content: Option<String>,

    /// Tool name for tool entries (e.g., "Edit", "Bash", "Read").
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tool_name: Option<String>,

    /// Tool detail — a description, file path, command, or URL.
    ///
    /// For verbose tools (Read, WebFetch, Skill), this shows only the
    /// path/URL, not the full content.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tool_detail: Option<String>,
}

impl CondensedEntry {
    /// Create a user prompt entry.
    pub fn user(content: impl Into<String>) -> Self {
        Self {
            entry_type: EntryType::User,
            content: Some(content.into()),
            tool_name: None,
            tool_detail: None,
        }
    }

    /// Create an assistant response entry.
    pub fn assistant(content: impl Into<String>) -> Self {
        Self {
            entry_type: EntryType::Assistant,
            content: Some(content.into()),
            tool_name: None,
            tool_detail: None,
        }
    }

    /// Create a tool invocation entry.
    pub fn tool(name: impl Into<String>, detail: Option<impl Into<String>>) -> Self {
        Self {
            entry_type: EntryType::Tool,
            content: None,
            tool_name: Some(name.into()),
            tool_detail: detail.map(Into::into),
        }
    }

    /// Returns true if this is a user entry.
    pub fn is_user(&self) -> bool {
        self.entry_type == EntryType::User
    }

    /// Returns true if this is an assistant entry.
    pub fn is_assistant(&self) -> bool {
        self.entry_type == EntryType::Assistant
    }

    /// Returns true if this is a tool entry.
    pub fn is_tool(&self) -> bool {
        self.entry_type == EntryType::Tool
    }
}

impl fmt::Display for CondensedEntry {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self.entry_type {
            EntryType::User => {
                write!(f, "[User] {}", self.content.as_deref().unwrap_or(""))
            }
            EntryType::Assistant => {
                write!(f, "[Assistant] {}", self.content.as_deref().unwrap_or(""))
            }
            EntryType::Tool => {
                let name = self.tool_name.as_deref().unwrap_or("Unknown");
                match &self.tool_detail {
                    Some(detail) => write!(f, "[Tool] {}: {}", name, detail),
                    None => write!(f, "[Tool] {}", name),
                }
            }
        }
    }
}

// Transcript Parsing (Claude Code JSONL)

/// Tools that should show only minimal detail (path/URL, not content).
const MINIMAL_DETAIL_TOOLS: &[&str] = &["Read", "Skill", "WebFetch"];

/// Prefix that identifies skill content injections in user messages.
///
/// Claude Code injects skill instructions as user messages after Skill tool
/// calls. These are verbose documentation, not user intent.
const SKILL_CONTENT_PREFIX: &str = "Base directory for this skill:";

/// Parse a Claude Code JSONL transcript into condensed entries.
///
/// Reads each line as JSON, extracts user prompts, assistant text responses,
/// and tool calls. Filters out:
/// - Skill content injections (verbose skill instructions in user messages)
/// - Full file contents from Read tool responses
/// - Verbose tool outputs
///
/// # Arguments
///
/// * `raw` — Raw JSONL bytes from the Claude Code transcript file
///
/// # Returns
///
/// A vector of condensed entries suitable for display and summarization.
/// Returns an empty vector if the transcript is empty or unparseable.
pub fn condense_claude_transcript(raw: &[u8]) -> Vec<CondensedEntry> {
    let mut entries = Vec::new();

    for line in raw.split(|&b| b == b'\n') {
        if line.is_empty() {
            continue;
        }

        let Ok(parsed) = serde_json::from_slice::<TranscriptLine>(line) else {
            continue;
        };

        match parsed.r#type.as_str() {
            "user" => {
                if let Some(content) = extract_user_content(&parsed.message) {
                    // Skip skill content injections
                    if !content.starts_with(SKILL_CONTENT_PREFIX) {
                        entries.push(CondensedEntry::user(content));
                    }
                }
            }
            "assistant" => {
                if let Ok(msg) = serde_json::from_value::<AssistantMessage>(parsed.message) {
                    for block in &msg.content {
                        match block.r#type.as_str() {
                            "text" if !block.text.is_empty() => {
                                entries.push(CondensedEntry::assistant(&block.text));
                            }
                            "tool_use" => {
                                let detail = extract_tool_detail(&block.name, &block.input);
                                entries.push(CondensedEntry::tool(&block.name, detail));
                            }
                            _ => {}
                        }
                    }
                }
            }
            _ => {}
        }
    }

    entries
}

/// Condense a transcript from raw bytes, auto-detecting format.
///
/// Currently supports Claude Code JSONL. Future: Gemini JSON, other formats.
pub fn condense_transcript(raw: &[u8], format: &str) -> Vec<CondensedEntry> {
    match format {
        "jsonl" => condense_claude_transcript(raw),
        // Future: "json" => condense_gemini_transcript(raw),
        _ => {
            log::warn!("Unknown transcript format '{}', returning empty", format);
            Vec::new()
        }
    }
}

/// Format condensed entries as human-readable text.
///
/// Output format:
/// ```text
/// [User] Fix the auth bug in login.rs
/// [Assistant] I'll fix the token validation...
/// [Tool] Edit: src/auth/login.rs
/// [Tool] Bash: cargo test
/// [Assistant] The fix is applied and tests pass.
///
/// [Files Modified]
/// - src/auth/login.rs
/// ```
///
/// This is the format passed to the reasoning generator and stored in
/// `UnhashedTurnData.condensed_text`.
pub fn format_condensed(entries: &[CondensedEntry], files: &[String]) -> String {
    let mut out = String::new();

    for (i, entry) in entries.iter().enumerate() {
        if i > 0 {
            out.push('\n');
        }
        out.push_str(&entry.to_string());
        out.push('\n');
    }

    if !files.is_empty() {
        out.push_str("\n[Files Modified]\n");
        for file in files {
            out.push_str("- ");
            out.push_str(file);
            out.push('\n');
        }
    }

    out
}

/// Extract user prompts from condensed entries.
pub fn extract_prompts(entries: &[CondensedEntry]) -> Vec<String> {
    entries
        .iter()
        .filter(|e| e.is_user())
        .filter_map(|e| e.content.clone())
        .collect()
}

/// Aggregate tool usage from condensed entries.
pub fn aggregate_tool_usage(entries: &[CondensedEntry]) -> Vec<ToolUseSummary> {
    let mut tools: HashMap<String, ToolUseSummary> = HashMap::new();

    for entry in entries.iter().filter(|e| e.is_tool()) {
        let name = entry.tool_name.as_deref().unwrap_or("Unknown");

        let summary = tools
            .entry(name.to_string())
            .or_insert_with(|| ToolUseSummary::new(name, 0, Vec::new()));

        summary.invocation_count += 1;

        // Track files affected by file-modifying tools
        if let Some(detail) = &entry.tool_detail {
            if matches!(name, "Edit" | "Write" | "MultiEdit" | "NotebookEdit")
                && !summary.files_affected.contains(detail) {
                    summary.files_affected.push(detail.clone());
                }
        }
    }

    let mut result: Vec<_> = tools.into_values().collect();
    result.sort_by(|a, b| a.tool_name.cmp(&b.tool_name));
    result
}

// Claude Code JSONL Types (internal)

/// A single line in a Claude Code JSONL transcript.
#[derive(Debug, Deserialize)]
struct TranscriptLine {
    r#type: String,
    #[allow(dead_code)]
    uuid: Option<String>,
    #[serde(default)]
    message: serde_json::Value,
}

/// An assistant message containing content blocks.
#[derive(Debug, Deserialize)]
struct AssistantMessage {
    content: Vec<ContentBlock>,
}

/// A content block within an assistant message.
#[derive(Debug, Deserialize)]
struct ContentBlock {
    r#type: String,
    #[serde(default)]
    text: String,
    #[serde(default)]
    name: String,
    #[serde(default)]
    input: serde_json::Value,
}

/// Tool input fields (best-effort extraction).
#[derive(Debug, Default, Deserialize)]
struct ToolInput {
    #[serde(default)]
    file_path: Option<String>,
    #[serde(default)]
    notebook_path: Option<String>,
    #[serde(default)]
    description: Option<String>,
    #[serde(default)]
    command: Option<String>,
    #[serde(default)]
    pattern: Option<String>,
    #[serde(default)]
    skill: Option<String>,
    #[serde(default)]
    url: Option<String>,
}

/// Extract user content from a transcript message value.
fn extract_user_content(message: &serde_json::Value) -> Option<String> {
    // User content can be a string or an array of content blocks
    if let Some(s) = message.get("content").and_then(|c| c.as_str()) {
        if !s.is_empty() {
            return Some(s.to_string());
        }
    }
    if let Some(arr) = message.get("content").and_then(|c| c.as_array()) {
        for item in arr {
            if let Some(text) = item.get("text").and_then(|t| t.as_str()) {
                if !text.is_empty() {
                    return Some(text.to_string());
                }
            }
            // Also handle plain string items in the array
            if let Some(text) = item.as_str() {
                if !text.is_empty() {
                    return Some(text.to_string());
                }
            }
        }
    }
    // Direct string message
    if let Some(s) = message.as_str() {
        if !s.is_empty() {
            return Some(s.to_string());
        }
    }
    None
}

/// Extract appropriate detail for a tool call.
///
/// For minimal-detail tools (Read, Skill, WebFetch), returns only the
/// essential identifier (path, skill name, URL). For other tools, returns
/// the most relevant field from the input.
fn extract_tool_detail(tool_name: &str, input: &serde_json::Value) -> Option<String> {
    let parsed: ToolInput = serde_json::from_value(input.clone()).unwrap_or_default();

    // Minimal detail tools — show only the identifier
    if MINIMAL_DETAIL_TOOLS.contains(&tool_name) {
        return match tool_name {
            "Skill" => parsed.skill,
            "Read" => parsed.file_path.or(parsed.notebook_path),
            "WebFetch" => parsed.url,
            _ => None,
        };
    }

    // Other tools — use the most relevant field
    parsed
        .description
        .or(parsed.command)
        .or(parsed.file_path)
        .or(parsed.notebook_path)
        .or(parsed.pattern)
}

// AI-Generated Reasoning Summary

/// AI-generated reasoning summary for a turn.
///
/// Captures what the agent learned during a turn — intent, outcome,
/// discoveries, problems, and deferred work. Generated by an LLM
/// (Claude CLI by default) from the condensed transcript.
///
/// Developers see learnings in terms of files, functions, and lines.
/// Under the hood, `anchor_to_graph()` attaches invisible CRDT references
/// so learnings automatically follow the code through renames and refactors.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct TurnReasoning {
    /// What the user was trying to accomplish (1-2 sentences).
    pub intent: String,

    /// What was actually achieved (1-2 sentences).
    pub outcome: String,

    /// Categorized discoveries made during the turn.
    pub learnings: Learnings,

    /// Problems, blockers, or annoyances encountered.
    #[serde(default)]
    pub friction: Vec<String>,

    /// Tech debt, unfinished work, or things to revisit later.
    #[serde(default)]
    pub open_items: Vec<String>,
}

impl TurnReasoning {
    /// Returns true if the reasoning has any code-specific learnings.
    pub fn has_code_learnings(&self) -> bool {
        !self.learnings.code.is_empty()
    }

    /// Returns the total number of learnings across all categories.
    pub fn learning_count(&self) -> usize {
        self.learnings.repo.len() + self.learnings.code.len() + self.learnings.workflow.len()
    }

    /// Returns true if the reasoning is essentially empty (no useful content).
    pub fn is_empty(&self) -> bool {
        self.intent.is_empty()
            && self.outcome.is_empty()
            && self.learnings.repo.is_empty()
            && self.learnings.code.is_empty()
            && self.learnings.workflow.is_empty()
            && self.friction.is_empty()
            && self.open_items.is_empty()
    }
}

impl fmt::Display for TurnReasoning {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        writeln!(f, "Intent: {}", self.intent)?;
        writeln!(f, "Outcome: {}", self.outcome)?;
        if !self.learnings.repo.is_empty() {
            writeln!(f, "Repo learnings:")?;
            for l in &self.learnings.repo {
                writeln!(f, "  • {}", l)?;
            }
        }
        if !self.learnings.code.is_empty() {
            writeln!(f, "Code learnings:")?;
            for l in &self.learnings.code {
                writeln!(f, "  • {}", l)?;
            }
        }
        if !self.learnings.workflow.is_empty() {
            writeln!(f, "Workflow learnings:")?;
            for l in &self.learnings.workflow {
                writeln!(f, "  • {}", l)?;
            }
        }
        if !self.friction.is_empty() {
            writeln!(f, "Friction:")?;
            for fr in &self.friction {
                writeln!(f, "  • {}", fr)?;
            }
        }
        if !self.open_items.is_empty() {
            writeln!(f, "Open items:")?;
            for item in &self.open_items {
                writeln!(f, "  • {}", item)?;
            }
        }
        Ok(())
    }
}

/// Categorized learnings from a turn.
#[derive(Clone, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct Learnings {
    /// Codebase-specific patterns, conventions, or gotchas.
    ///
    /// Examples:
    /// - "Auth module uses JWT with RS256, not HS256"
    /// - "Database migrations are in migrations/ not db/"
    #[serde(default)]
    pub repo: Vec<String>,

    /// Findings about specific code locations.
    ///
    /// Each learning is tied to a file (and optionally function/line).
    /// The `_anchor` field (when populated) keeps the learning attached
    /// to the code as it moves through renames and refactors.
    #[serde(default)]
    pub code: Vec<CodeLearning>,

    /// General development practices or tool usage insights.
    ///
    /// Examples:
    /// - "cargo test --lib is faster for auth changes"
    /// - "Dev server needs restart after config.toml changes"
    #[serde(default)]
    pub workflow: Vec<String>,
}

impl Learnings {
    /// Returns the total number of learnings across all categories.
    pub fn total(&self) -> usize {
        self.repo.len() + self.code.len() + self.workflow.len()
    }

    /// Returns true if there are no learnings in any category.
    pub fn is_empty(&self) -> bool {
        self.repo.is_empty() && self.code.is_empty() && self.workflow.is_empty()
    }
}

/// A learning tied to a specific code location.
///
/// # User-Facing Fields
///
/// Developers see: file path, line number, function name, and the finding
/// in plain language. These are what appears in `atomic log --learnings`
/// and in the server UI.
///
/// # Graph Anchor (Invisible)
///
/// The `_anchor` field contains CRDT references (TrunkId, BranchId, LeafId)
/// that keep the learning attached to the specific tokens in the graph.
/// This is populated by `anchor_to_graph()` after recording and is never
/// shown in CLI output. The server uses it to resolve the learning to the
/// current file/line position even after renames and refactors.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct CodeLearning {
    /// File path (e.g., `"src/auth/login.rs"`).
    pub path: String,

    /// Line number at recording time.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub line: Option<u32>,

    /// End line for multi-line ranges.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub end_line: Option<u32>,

    /// Function or method name, if identifiable.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub function: Option<String>,

    /// What was learned, in plain language.
    pub finding: String,

    /// Category of the finding.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub category: Option<String>,

    /// CRDT graph anchor — invisible to users, used by server for tracking.
    ///
    /// Populated by `anchor_to_graph()` from the change's `FileOps`.
    /// Contains TrunkId (file), BranchId (lines), LeafId (tokens) that
    /// keep this learning attached to the code as it moves.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub _anchor: Option<GraphAnchor>,
}

impl CodeLearning {
    /// Create a new code learning with the minimum required fields.
    pub fn new(path: impl Into<String>, line: Option<u32>, finding: impl Into<String>) -> Self {
        Self {
            path: path.into(),
            line,
            end_line: None,
            function: None,
            finding: finding.into(),
            category: None,
            _anchor: None,
        }
    }

    /// Set the function name.
    #[must_use]
    pub fn with_function(mut self, function: impl Into<String>) -> Self {
        self.function = Some(function.into());
        self
    }

    /// Set the end line for a range.
    #[must_use]
    pub fn with_end_line(mut self, end_line: u32) -> Self {
        self.end_line = Some(end_line);
        self
    }

    /// Set the category.
    #[must_use]
    pub fn with_category(mut self, category: impl Into<String>) -> Self {
        self.category = Some(category.into());
        self
    }

    /// Returns true if this learning has a graph anchor.
    pub fn is_anchored(&self) -> bool {
        self._anchor.is_some()
    }
}

impl fmt::Display for CodeLearning {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.path)?;
        if let Some(line) = self.line {
            write!(f, ":{}", line)?;
            if let Some(end) = self.end_line {
                write!(f, "-{}", end)?;
            }
        }
        if let Some(ref func) = self.function {
            write!(f, " ({})", func)?;
        }
        write!(f, " — {}", self.finding)?;
        if let Some(ref cat) = self.category {
            write!(f, " [{}]", cat)?;
        }
        Ok(())
    }
}

// Graph Anchor (invisible to users)

/// CRDT graph references that keep a learning anchored to specific code.
///
/// This is populated from the change's `FileOps` by `anchor_to_graph()`.
/// The server resolves these IDs to current file/line positions when
/// displaying learnings. Users never see this — they see files and lines.
///
/// If the referenced code is renamed or moved, the TrunkId/BranchId/LeafId
/// still resolve correctly because they're part of the graph, not computed
/// from file position.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct GraphAnchor {
    /// TrunkId as (change_id, file_idx) — the file, survives renames.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub trunk: Option<(u64, u32)>,

    /// BranchIds as (change_id, branch_idx) — the lines, survive insertions.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub branches: Vec<(u64, u32)>,

    /// LeafIds as (change_id, leaf_idx) — the tokens, survive refactors.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub leaves: Vec<(u64, u32)>,
}

impl GraphAnchor {
    /// Create an empty anchor.
    pub fn empty() -> Self {
        Self {
            trunk: None,
            branches: Vec::new(),
            leaves: Vec::new(),
        }
    }

    /// Returns true if this anchor has any references.
    pub fn is_populated(&self) -> bool {
        self.trunk.is_some() || !self.branches.is_empty() || !self.leaves.is_empty()
    }
}

/// Anchor code learnings to the CRDT graph using FileOps from the recorded change.
///
/// This is a post-processing step called after the LLM returns human-readable
/// findings. For each `CodeLearning`, it looks up the file path and line number
/// in the change's `FileOps` to find the corresponding TrunkId, BranchId, and
/// LeafId references.
///
/// # Arguments
///
/// * `learnings` — The code learnings to anchor (modified in place)
/// * `file_ops` — The CRDT operations from the recorded change
///
/// # Behavior
///
/// - If a learning's `path` matches a `FileOps.path()`, the `trunk` is set
/// - If a learning's `line` matches a `LineOps` line number, `branches` are set
/// - `leaves` are populated from the `LeafOp`s of matched lines
/// - If no match is found, the anchor is left as `None` (the learning still
///   works, just without auto-tracking through renames/refactors)
pub fn anchor_to_graph(learnings: &mut [CodeLearning], file_ops: &[atomic_core::change::FileOps]) {
    for learning in learnings.iter_mut() {
        let mut anchor = GraphAnchor::empty();

        // Find the matching file in FileOps
        for fop in file_ops {
            if fop.path() != learning.path {
                continue;
            }

            // Set trunk anchor (file level)
            let tid = fop.trunk_id();
            anchor.trunk = Some((tid.change_id().get(), tid.file_idx()));

            // If we have a line number, try to match line operations
            if let Some(target_line) = learning.line {
                for line_op in fop.line_ops() {
                    // Check both old and new line numbers — deletes have old,
                    // inserts have new, some ops have both
                    let op_line = line_op.new_line_num().or_else(|| line_op.old_line_num());
                    let matches = match (op_line, learning.end_line) {
                        (Some(l), Some(end)) => l as u32 >= target_line && (l as u32) <= end,
                        (Some(l), None) => l as u32 == target_line,
                        (None, _) => false,
                    };

                    if matches {
                        let bid = line_op.branch_id();
                        anchor
                            .branches
                            .push((bid.change_id().get(), bid.branch_idx()));

                        // Collect leaf IDs from the line's operations
                        for leaf_op in line_op.leaf_ops() {
                            if let Some(lid) = leaf_op_id(leaf_op) {
                                anchor.leaves.push(lid);
                            }
                        }
                    }
                }
            }

            break; // Found the file, done
        }

        if anchor.is_populated() {
            learning._anchor = Some(anchor);
        }
    }
}

// Reasoning Generator Trait + Claude CLI Implementation

/// The summarization prompt template.
///
/// Wraps the transcript in `<transcript>` tags to provide clear boundary markers.
/// This helps contain any potentially malicious content within the transcript
/// (e.g., prompt injection attempts in user messages or file contents) by giving
/// the LLM a clear structural signal about where the untrusted content begins
/// and ends.
///
/// The prompt asks the LLM to return code learnings with file paths, line numbers,
/// and function names. The `anchor_to_graph()` post-processing step then silently
/// attaches CRDT references from the change's `FileOps`.
const SUMMARIZATION_PROMPT: &str = r#"Analyze this development session transcript and generate a structured summary.

<transcript>
{transcript}
</transcript>

Return a JSON object with this exact structure:
{
  "intent": "What the user was trying to accomplish (1-2 sentences)",
  "outcome": "What was actually achieved (1-2 sentences)",
  "learnings": {
    "repo": ["Codebase-specific patterns, conventions, or gotchas discovered"],
    "code": [{"path": "file/path.rs", "line": 42, "function": "function_name", "finding": "What was learned", "category": "bug|pattern|convention|performance|security"}],
    "workflow": ["General development practices or tool usage insights"]
  },
  "friction": ["Problems, blockers, or annoyances encountered"],
  "open_items": ["Tech debt, unfinished work, or things to revisit later"]
}

Guidelines:
- Be concise but specific
- Include file paths and line numbers for code learnings when the transcript references them
- Include function names when identifiable
- Categorize code learnings: bug, pattern, convention, performance, or security
- Friction should capture both blockers and minor annoyances
- Open items are things intentionally deferred, not failures
- Empty arrays are fine if a category doesn't apply
- Return ONLY the JSON object, no markdown formatting or explanation"#;

/// Default Claude CLI model for summarization.
///
/// Sonnet provides a good balance of quality and cost.
const DEFAULT_MODEL: &str = "sonnet";

/// Trait for generating reasoning summaries from condensed transcripts.
///
/// Implementations can use different backends: Claude CLI, a local model,
/// an API endpoint, or a mock for testing.
///
/// # Example
///
/// ```rust,ignore
/// use atomic_agent::transcript::{ReasoningGenerator, ClaudeCliGenerator};
///
/// let generator = ClaudeCliGenerator::new();
/// let reasoning = generator.generate("condensed transcript text", &["file.rs"])?;
/// println!("Intent: {}", reasoning.intent);
/// ```
pub trait ReasoningGenerator: Send + Sync {
    /// Generate a reasoning summary from a condensed transcript.
    ///
    /// # Arguments
    ///
    /// * `condensed_text` — The formatted condensed transcript
    ///   (`[User]/[Assistant]/[Tool]` format from `format_condensed()`)
    /// * `files` — List of files modified in this turn
    ///
    /// # Returns
    ///
    /// A `TurnReasoning` with intent, outcome, learnings, friction, and open items.
    ///
    /// # Errors
    ///
    /// Returns `AgentError::Internal` if generation fails (LLM not available,
    /// parse error, etc.). Callers should treat this as non-fatal — reasoning
    /// is optional enrichment, not required for recording.
    fn generate(&self, condensed_text: &str, files: &[String]) -> AgentResult<TurnReasoning>;
}

/// Generates reasoning summaries by calling the Claude CLI.
///
/// Runs `claude --print --output-format json` as a subprocess, passing the
/// condensed transcript via stdin. The subprocess is fully isolated from the
/// user's repository to prevent recursive hook triggering and git index pollution.
///
/// # Isolation
///
/// - `cmd.Dir` is set to a temp directory (not the repo)
/// - `GIT_*` environment variables are stripped
/// - `--setting-sources ""` skips all Claude Code settings (hooks, MCP, etc.)
///
/// # Error Handling
///
/// All errors are non-fatal. If Claude CLI is not installed, the subprocess
/// fails, or the response can't be parsed, an error is returned and the caller
/// logs a warning. The change is still recorded without reasoning.
///
/// # Example
///
/// ```rust,ignore
/// use atomic_agent::transcript::{ClaudeCliGenerator, ReasoningGenerator};
///
/// let generator = ClaudeCliGenerator::new();
/// match generator.generate("transcript text", &["file.rs"]) {
///     Ok(reasoning) => println!("Intent: {}", reasoning.intent),
///     Err(e) => eprintln!("Reasoning generation failed (non-fatal): {}", e),
/// }
/// ```
#[derive(Debug, Clone)]
pub struct ClaudeCliGenerator {
    /// Path to the claude CLI executable.
    ///
    /// If `None`, uses `"claude"` (expects it to be in `PATH`).
    pub claude_path: Option<PathBuf>,

    /// Claude model to use for summarization.
    ///
    /// Defaults to `"sonnet"` if not set.
    pub model: Option<String>,

    /// Timeout in seconds for the Claude CLI subprocess.
    ///
    /// Defaults to 60 seconds.
    pub timeout_secs: u64,
}

impl ClaudeCliGenerator {
    /// Create a new generator with default settings.
    pub fn new() -> Self {
        Self {
            claude_path: None,
            model: None,
            timeout_secs: 60,
        }
    }

    /// Set the path to the claude CLI executable.
    #[must_use]
    pub fn with_claude_path(mut self, path: impl Into<PathBuf>) -> Self {
        self.claude_path = Some(path.into());
        self
    }

    /// Set the model to use.
    #[must_use]
    pub fn with_model(mut self, model: impl Into<String>) -> Self {
        self.model = Some(model.into());
        self
    }

    /// Set the timeout in seconds.
    #[must_use]
    pub fn with_timeout(mut self, secs: u64) -> Self {
        self.timeout_secs = secs;
        self
    }

    /// Get the effective claude CLI path.
    fn claude_path(&self) -> &str {
        self.claude_path
            .as_ref()
            .and_then(|p| p.to_str())
            .unwrap_or("claude")
    }

    /// Get the effective model name.
    fn model(&self) -> &str {
        self.model.as_deref().unwrap_or(DEFAULT_MODEL)
    }

    /// Build the summarization prompt from the condensed transcript.
    fn build_prompt(&self, condensed_text: &str) -> String {
        SUMMARIZATION_PROMPT.replace("{transcript}", condensed_text)
    }

    /// Strip GIT_* environment variables to prevent the subprocess from
    /// discovering or modifying the parent's git repo.
    fn clean_env() -> Vec<(String, String)> {
        std::env::vars()
            .filter(|(key, _)| !key.starts_with("GIT_"))
            .collect()
    }

    /// Check if the claude CLI is available on PATH.
    pub fn is_available(&self) -> bool {
        Command::new(self.claude_path())
            .arg("--version")
            .stdout(std::process::Stdio::null())
            .stderr(std::process::Stdio::null())
            .status()
            .is_ok()
    }
}

impl Default for ClaudeCliGenerator {
    fn default() -> Self {
        Self::new()
    }
}

impl ReasoningGenerator for ClaudeCliGenerator {
    fn generate(&self, condensed_text: &str, _files: &[String]) -> AgentResult<TurnReasoning> {
        let prompt = self.build_prompt(condensed_text);
        let claude_path = self.claude_path();
        let model = self.model();

        // Build the command
        // --print: output to stdout instead of interactive mode
        // --output-format json: wrap response in {"result": "..."} JSON
        // --model: which model to use
        // --setting-sources "": skip all settings (hooks, MCP, etc.)
        let mut cmd = Command::new(claude_path);
        cmd.args([
            "--print",
            "--output-format",
            "json",
            "--model",
            model,
            "--setting-sources",
            "",
        ]);

        // Isolate the subprocess from the user's repository
        cmd.current_dir(std::env::temp_dir());
        cmd.env_clear();
        for (key, value) in Self::clean_env() {
            cmd.env(&key, &value);
        }

        // Pass prompt via stdin
        cmd.stdin(std::process::Stdio::piped());
        cmd.stdout(std::process::Stdio::piped());
        cmd.stderr(std::process::Stdio::piped());

        // Spawn the process
        let mut child = cmd.spawn().map_err(|e| {
            if e.kind() == std::io::ErrorKind::NotFound {
                AgentError::Internal(format!(
                    "Claude CLI not found at '{}'. Install from https://docs.anthropic.com/en/docs/claude-code",
                    claude_path
                ))
            } else {
                AgentError::Internal(format!("Failed to spawn Claude CLI: {}", e))
            }
        })?;

        // Write prompt to stdin
        if let Some(mut stdin) = child.stdin.take() {
            let _ = stdin.write_all(prompt.as_bytes());
            // stdin is dropped here, closing the pipe
        }

        // Wait for the process with timeout
        let output = child
            .wait_with_output()
            .map_err(|e| AgentError::Internal(format!("Claude CLI process failed: {}", e)))?;

        if !output.status.success() {
            let stderr = String::from_utf8_lossy(&output.stderr);
            return Err(AgentError::Internal(format!(
                "Claude CLI exited with code {}: {}",
                output.status.code().unwrap_or(-1),
                stderr.trim(),
            )));
        }

        // Parse the CLI JSON response: {"result": "...actual JSON..."}
        let stdout = String::from_utf8_lossy(&output.stdout);
        let cli_response: serde_json::Value = serde_json::from_str(&stdout).map_err(|e| {
            AgentError::Internal(format!(
                "Failed to parse Claude CLI response as JSON: {} (response: {})",
                e,
                truncate_for_error(&stdout, 200),
            ))
        })?;

        // Extract the "result" field which contains the actual summary JSON
        let result_str = cli_response
            .get("result")
            .and_then(|v| v.as_str())
            .ok_or_else(|| {
                AgentError::Internal(format!(
                    "Claude CLI response missing 'result' field: {}",
                    truncate_for_error(&stdout, 200),
                ))
            })?;

        // The result may be wrapped in markdown code blocks — strip them
        let clean_json = strip_markdown_code_blocks(result_str);

        // Parse the summary JSON into TurnReasoning
        let reasoning: TurnReasoning = serde_json::from_str(&clean_json).map_err(|e| {
            AgentError::Internal(format!(
                "Failed to parse reasoning JSON: {} (json: {})",
                e,
                truncate_for_error(&clean_json, 300),
            ))
        })?;

        Ok(reasoning)
    }
}

/// Strip markdown code block wrappers from a JSON string.
///
/// Claude sometimes wraps JSON in ```json ... ``` blocks despite being
/// asked not to. This strips those wrappers.
fn strip_markdown_code_blocks(s: &str) -> String {
    let trimmed = s.trim();

    // Check for ```json ... ``` blocks
    if let Some(rest) = trimmed.strip_prefix("```json") {
        if let Some(idx) = rest.rfind("```") {
            return rest[..idx].trim().to_string();
        }
    }

    // Check for ``` ... ``` blocks
    if let Some(rest) = trimmed.strip_prefix("```") {
        if let Some(idx) = rest.rfind("```") {
            return rest[..idx].trim().to_string();
        }
    }

    trimmed.to_string()
}

/// Truncate a string for display in log messages and UI.
///
/// Adds "..." suffix if truncated. Used for intent/outcome summaries
/// in log output.
pub fn truncate_for_display(s: &str, max_len: usize) -> String {
    if s.len() <= max_len {
        return s.to_string();
    }
    let truncated: String = s.chars().take(max_len.saturating_sub(3)).collect();
    format!("{}...", truncated)
}

/// Truncate a string for inclusion in error messages.
fn truncate_for_error(s: &str, max_len: usize) -> String {
    if s.len() <= max_len {
        s.to_string()
    } else {
        format!("{}...", &s[..max_len])
    }
}

/// Generate reasoning from a condensed transcript using the default generator.
///
/// This is a convenience function that creates a `ClaudeCliGenerator` with
/// default settings. For custom configuration, create the generator directly.
///
/// # Arguments
///
/// * `condensed_text` — The formatted condensed transcript
/// * `files` — List of files modified in this turn
///
/// # Returns
///
/// `Ok(TurnReasoning)` on success, `Err` if Claude CLI is not available
/// or generation fails.
pub fn generate_reasoning(condensed_text: &str, files: &[String]) -> AgentResult<TurnReasoning> {
    let generator = ClaudeCliGenerator::new();
    generator.generate(condensed_text, files)
}

/// Generate reasoning if Claude CLI is available, returning None if not.
///
/// This is the non-fatal version — returns `None` instead of an error when
/// Claude CLI is not installed or generation fails. Suitable for the
/// recording pipeline where reasoning is optional enrichment.
pub fn try_generate_reasoning(condensed_text: &str, files: &[String]) -> Option<TurnReasoning> {
    let generator = ClaudeCliGenerator::new();

    if !generator.is_available() {
        log::debug!("Claude CLI not available — skipping reasoning generation");
        return None;
    }

    match generator.generate(condensed_text, files) {
        Ok(reasoning) => {
            if reasoning.is_empty() {
                log::debug!("Reasoning generator returned empty result — skipping");
                None
            } else {
                Some(reasoning)
            }
        }
        Err(e) => {
            log::warn!("Reasoning generation failed (non-fatal): {}", e);
            None
        }
    }
}

// Mock Generator (for testing)

/// A mock reasoning generator for testing.
///
/// Returns a fixed `TurnReasoning` regardless of input, or an error if
/// configured to fail.
#[cfg(test)]
pub struct MockGenerator {
    result: Result<TurnReasoning, String>,
}

#[cfg(test)]
impl MockGenerator {
    /// Create a mock that returns a successful reasoning.
    pub fn success(reasoning: TurnReasoning) -> Self {
        Self {
            result: Ok(reasoning),
        }
    }

    /// Create a mock that returns an error.
    pub fn failure(message: &str) -> Self {
        Self {
            result: Err(message.to_string()),
        }
    }
}

#[cfg(test)]
impl ReasoningGenerator for MockGenerator {
    fn generate(&self, _condensed_text: &str, _files: &[String]) -> AgentResult<TurnReasoning> {
        match &self.result {
            Ok(r) => Ok(r.clone()),
            Err(msg) => Err(AgentError::Internal(msg.clone())),
        }
    }
}

// CRDT Anchor Helpers

/// Extract the (change_id, leaf_idx) tuple from a LeafOp, if it references an existing leaf.
///
/// Insert ops don't carry an assigned LeafId (the ID is assigned during apply),
/// so they return None. Delete, Replace, and Restore reference existing leaves.
fn leaf_op_id(op: &atomic_core::crdt::LeafOp) -> Option<(u64, u32)> {
    op.leaf_id()
        .map(|lid| (lid.change_id().get(), lid.leaf_idx()))
}

// Tool Usage Summary

/// Aggregated tool usage for a turn.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct ToolUseSummary {
    /// Tool name (e.g., "Edit", "Bash", "Read").
    pub tool_name: String,

    /// Number of times the tool was invoked in this turn.
    pub invocation_count: u32,

    /// Files affected by this tool (deduplicated).
    #[serde(default)]
    pub files_affected: Vec<String>,
}

impl ToolUseSummary {
    /// Create a new tool usage summary.
    pub fn new(name: impl Into<String>, count: u32, files: Vec<String>) -> Self {
        Self {
            tool_name: name.into(),
            invocation_count: count,
            files_affected: files,
        }
    }
}

impl fmt::Display for ToolUseSummary {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{} (×{})", self.tool_name, self.invocation_count)?;
        if !self.files_affected.is_empty() {
            write!(f, " → {}", self.files_affected.join(", "))?;
        }
        Ok(())
    }
}

// Unhashed Turn Data

/// The top-level unhashed data for an agent turn.
///
/// Stored in `change.unhashed["agent_turn"]`. Contains the condensed
/// transcript, extracted prompts, tool usage, and optional AI-generated
/// reasoning summary.
///
/// This is unhashed so it can be:
/// - Stripped from public repos (set `redacted: true`)
/// - Regenerated with a better model
/// - Different across clones (interpretation, not fact)
///
/// The change hash is NOT affected by any of this data.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct UnhashedTurnData {
    /// Session identifier (links to other turns in the same session).
    pub session_id: String,

    /// Turn number within the session (1-indexed).
    pub turn_number: u32,

    /// Transcript format: "jsonl" (Claude), "json" (Gemini), "markdown" (other).
    pub transcript_format: String,

    /// Structured condensed transcript entries.
    pub condensed_transcript: Vec<CondensedEntry>,

    /// Human-readable formatted transcript text.
    ///
    /// This is `format_condensed()` output — the `[User]/[Assistant]/[Tool]`
    /// format used for display and as input to the reasoning generator.
    pub condensed_text: String,

    /// Extracted user prompts for quick access and search.
    #[serde(default)]
    pub prompts: Vec<String>,

    /// Aggregated tool usage statistics.
    #[serde(default)]
    pub tools_used: Vec<ToolUseSummary>,

    /// AI-generated reasoning summary.
    ///
    /// `None` if reasoning generation is disabled or failed.
    /// Contains intent, outcome, learnings, friction, and open items.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reasoning: Option<TurnReasoning>,

    /// Whether the transcript/reasoning has been stripped for privacy.
    ///
    /// When `true`, `condensed_transcript` and `reasoning` are empty/None.
    /// The server shows a "redacted" badge instead of the transcript viewer.
    #[serde(default)]
    pub redacted: bool,
}

impl UnhashedTurnData {
    /// Create a minimal unhashed data struct (no reasoning).
    pub fn new(
        session_id: impl Into<String>,
        turn_number: u32,
        format: impl Into<String>,
        entries: Vec<CondensedEntry>,
        files: &[String],
    ) -> Self {
        let condensed_text = format_condensed(&entries, files);
        let prompts = extract_prompts(&entries);
        let tools_used = aggregate_tool_usage(&entries);

        Self {
            session_id: session_id.into(),
            turn_number,
            transcript_format: format.into(),
            condensed_transcript: entries,
            condensed_text,
            prompts,
            tools_used,
            reasoning: None,
            redacted: false,
        }
    }

    /// Set the reasoning summary.
    pub fn with_reasoning(mut self, reasoning: TurnReasoning) -> Self {
        self.reasoning = Some(reasoning);
        self
    }

    /// Returns true if this data has a reasoning summary.
    pub fn has_reasoning(&self) -> bool {
        self.reasoning.is_some()
    }

    /// Returns true if this data has been redacted.
    pub fn is_redacted(&self) -> bool {
        self.redacted
    }

    /// Returns the number of condensed transcript entries.
    pub fn entry_count(&self) -> usize {
        self.condensed_transcript.len()
    }
}

// Attach / Extract / Strip operations on Change.unhashed

/// The JSON key used to store agent turn data in `change.unhashed`.
pub const UNHASHED_KEY: &str = "agent_turn";

/// Attach unhashed turn data to a change.
///
/// Serializes `UnhashedTurnData` as JSON and stores it under the
/// `"agent_turn"` key in `change.unhashed`. Creates the unhashed
/// JSON object if it doesn't exist.
pub fn attach_unhashed(
    change: &mut atomic_core::change::Change,
    data: &UnhashedTurnData,
) -> Result<(), serde_json::Error> {
    let value = serde_json::to_value(data)?;

    let unhashed = change.unhashed.get_or_insert_with(|| serde_json::json!({}));

    if let Some(obj) = unhashed.as_object_mut() {
        obj.insert(UNHASHED_KEY.to_string(), value);
    }

    Ok(())
}

/// Extract unhashed turn data from a change.
///
/// Returns `None` if the change has no unhashed data or no `"agent_turn"` key.
pub fn extract_unhashed(change: &atomic_core::change::Change) -> Option<UnhashedTurnData> {
    let unhashed = change.unhashed.as_ref()?;
    let agent_turn = unhashed.get(UNHASHED_KEY)?;
    serde_json::from_value(agent_turn.clone()).ok()
}

/// Strip transcript and reasoning from a change for privacy.
///
/// Replaces the unhashed turn data with a minimal stub that has
/// `redacted: true`. The change hash is NOT affected.
///
/// Returns `true` if data was stripped, `false` if there was nothing to strip.
pub fn strip_unhashed(change: &mut atomic_core::change::Change) -> bool {
    let Some(unhashed) = change.unhashed.as_mut() else {
        return false;
    };
    let Some(obj) = unhashed.as_object_mut() else {
        return false;
    };

    if !obj.contains_key(UNHASHED_KEY) {
        return false;
    }

    // Extract just the session_id and turn_number for the stub
    let stub = if let Some(existing) = obj.get(UNHASHED_KEY) {
        let session_id = existing
            .get("session_id")
            .and_then(|v| v.as_str())
            .unwrap_or("")
            .to_string();
        let turn_number = existing
            .get("turn_number")
            .and_then(|v| v.as_u64())
            .unwrap_or(0) as u32;

        serde_json::json!({
            "session_id": session_id,
            "turn_number": turn_number,
            "transcript_format": "redacted",
            "condensed_transcript": [],
            "condensed_text": "",
            "prompts": [],
            "tools_used": [],
            "reasoning": null,
            "redacted": true
        })
    } else {
        serde_json::json!({ "redacted": true })
    };

    obj.insert(UNHASHED_KEY.to_string(), stub);
    true
}

/// Check if a change has unhashed agent turn data.
pub fn has_unhashed(change: &atomic_core::change::Change) -> bool {
    change
        .unhashed
        .as_ref()
        .and_then(|v| v.get(UNHASHED_KEY))
        .is_some()
}

/// Check if a change's unhashed data has been redacted.
pub fn is_redacted(change: &atomic_core::change::Change) -> bool {
    change
        .unhashed
        .as_ref()
        .and_then(|v| v.get(UNHASHED_KEY))
        .and_then(|v| v.get("redacted"))
        .and_then(|v| v.as_bool())
        .unwrap_or(false)
}

// Tests

#[cfg(test)]
mod tests {
    use super::*;

    // CondensedEntry

    #[test]
    fn test_entry_user() {
        let e = CondensedEntry::user("Fix the bug");
        assert!(e.is_user());
        assert!(!e.is_assistant());
        assert!(!e.is_tool());
        assert_eq!(e.content.as_deref(), Some("Fix the bug"));
    }

    #[test]
    fn test_entry_assistant() {
        let e = CondensedEntry::assistant("I'll fix it");
        assert!(e.is_assistant());
        assert_eq!(e.content.as_deref(), Some("I'll fix it"));
    }

    #[test]
    fn test_entry_tool() {
        let e = CondensedEntry::tool("Edit", Some("src/main.rs"));
        assert!(e.is_tool());
        assert_eq!(e.tool_name.as_deref(), Some("Edit"));
        assert_eq!(e.tool_detail.as_deref(), Some("src/main.rs"));
    }

    #[test]
    fn test_entry_tool_no_detail() {
        let e = CondensedEntry::tool("Bash", None::<String>);
        assert!(e.is_tool());
        assert!(e.tool_detail.is_none());
    }

    #[test]
    fn test_entry_display_user() {
        let e = CondensedEntry::user("hello");
        assert_eq!(e.to_string(), "[User] hello");
    }

    #[test]
    fn test_entry_display_assistant() {
        let e = CondensedEntry::assistant("response");
        assert_eq!(e.to_string(), "[Assistant] response");
    }

    #[test]
    fn test_entry_display_tool_with_detail() {
        let e = CondensedEntry::tool("Edit", Some("file.rs"));
        assert_eq!(e.to_string(), "[Tool] Edit: file.rs");
    }

    #[test]
    fn test_entry_display_tool_no_detail() {
        let e = CondensedEntry::tool("Bash", None::<String>);
        assert_eq!(e.to_string(), "[Tool] Bash");
    }

    #[test]
    fn test_entry_serde_roundtrip() {
        let entries = vec![
            CondensedEntry::user("prompt"),
            CondensedEntry::assistant("response"),
            CondensedEntry::tool("Edit", Some("file.rs")),
        ];
        let json = serde_json::to_string(&entries).unwrap();
        let parsed: Vec<CondensedEntry> = serde_json::from_str(&json).unwrap();
        assert_eq!(entries, parsed);
    }

    // Transcript parsing (Claude Code JSONL)

    #[test]
    fn test_condense_empty() {
        let entries = condense_claude_transcript(b"");
        assert!(entries.is_empty());
    }

    #[test]
    fn test_condense_user_message() {
        let jsonl = br#"{"type":"user","uuid":"1","message":{"content":"Fix the bug"}}"#;
        let entries = condense_claude_transcript(jsonl);
        assert_eq!(entries.len(), 1);
        assert!(entries[0].is_user());
        assert_eq!(entries[0].content.as_deref(), Some("Fix the bug"));
    }

    #[test]
    fn test_condense_assistant_text() {
        let jsonl = br#"{"type":"assistant","uuid":"2","message":{"content":[{"type":"text","text":"I'll fix it"}]}}"#;
        let entries = condense_claude_transcript(jsonl);
        assert_eq!(entries.len(), 1);
        assert!(entries[0].is_assistant());
        assert_eq!(entries[0].content.as_deref(), Some("I'll fix it"));
    }

    #[test]
    fn test_condense_tool_use() {
        let jsonl = br#"{"type":"assistant","uuid":"3","message":{"content":[{"type":"tool_use","name":"Edit","input":{"file_path":"src/main.rs"}}]}}"#;
        let entries = condense_claude_transcript(jsonl);
        assert_eq!(entries.len(), 1);
        assert!(entries[0].is_tool());
        assert_eq!(entries[0].tool_name.as_deref(), Some("Edit"));
        assert_eq!(entries[0].tool_detail.as_deref(), Some("src/main.rs"));
    }

    #[test]
    fn test_condense_filters_skill_injection() {
        let jsonl = br#"{"type":"user","uuid":"4","message":{"content":"Base directory for this skill: /path/to/skill...long content..."}}"#;
        let entries = condense_claude_transcript(jsonl);
        assert!(entries.is_empty());
    }

    #[test]
    fn test_condense_minimal_detail_read() {
        let jsonl = br#"{"type":"assistant","uuid":"5","message":{"content":[{"type":"tool_use","name":"Read","input":{"file_path":"src/lib.rs"}}]}}"#;
        let entries = condense_claude_transcript(jsonl);
        assert_eq!(entries.len(), 1);
        assert_eq!(entries[0].tool_detail.as_deref(), Some("src/lib.rs"));
    }

    #[test]
    fn test_condense_bash_with_command() {
        let jsonl = br#"{"type":"assistant","uuid":"6","message":{"content":[{"type":"tool_use","name":"Bash","input":{"command":"cargo test"}}]}}"#;
        let entries = condense_claude_transcript(jsonl);
        assert_eq!(entries.len(), 1);
        assert_eq!(entries[0].tool_detail.as_deref(), Some("cargo test"));
    }

    #[test]
    fn test_condense_multi_line() {
        let jsonl = b"
{\"type\":\"user\",\"uuid\":\"1\",\"message\":{\"content\":\"Hello\"}}
{\"type\":\"assistant\",\"uuid\":\"2\",\"message\":{\"content\":[{\"type\":\"text\",\"text\":\"Hi\"}]}}
{\"type\":\"assistant\",\"uuid\":\"3\",\"message\":{\"content\":[{\"type\":\"tool_use\",\"name\":\"Edit\",\"input\":{\"file_path\":\"a.rs\"}}]}}
";
        let entries = condense_claude_transcript(jsonl);
        assert_eq!(entries.len(), 3);
        assert!(entries[0].is_user());
        assert!(entries[1].is_assistant());
        assert!(entries[2].is_tool());
    }

    #[test]
    fn test_condense_skips_malformed_lines() {
        let jsonl = b"not json\n{\"type\":\"user\",\"uuid\":\"1\",\"message\":{\"content\":\"valid\"}}\nalso not json";
        let entries = condense_claude_transcript(jsonl);
        assert_eq!(entries.len(), 1);
        assert_eq!(entries[0].content.as_deref(), Some("valid"));
    }

    #[test]
    fn test_condense_transcript_unknown_format() {
        let entries = condense_transcript(b"data", "unknown");
        assert!(entries.is_empty());
    }

    // format_condensed

    #[test]
    fn test_format_condensed_empty() {
        let text = format_condensed(&[], &[]);
        assert!(text.is_empty());
    }

    #[test]
    fn test_format_condensed_with_entries() {
        let entries = vec![
            CondensedEntry::user("Hello"),
            CondensedEntry::assistant("Hi"),
        ];
        let text = format_condensed(&entries, &[]);
        assert!(text.contains("[User] Hello"));
        assert!(text.contains("[Assistant] Hi"));
    }

    #[test]
    fn test_format_condensed_with_files() {
        let entries = vec![CondensedEntry::user("Fix it")];
        let files = vec!["src/main.rs".to_string()];
        let text = format_condensed(&entries, &files);
        assert!(text.contains("[Files Modified]"));
        assert!(text.contains("- src/main.rs"));
    }

    // extract_prompts

    #[test]
    fn test_extract_prompts() {
        let entries = vec![
            CondensedEntry::user("First prompt"),
            CondensedEntry::assistant("Response"),
            CondensedEntry::user("Second prompt"),
            CondensedEntry::tool("Edit", Some("file.rs")),
        ];
        let prompts = extract_prompts(&entries);
        assert_eq!(prompts, vec!["First prompt", "Second prompt"]);
    }

    #[test]
    fn test_extract_prompts_empty() {
        let entries = vec![CondensedEntry::assistant("No user messages")];
        let prompts = extract_prompts(&entries);
        assert!(prompts.is_empty());
    }

    // aggregate_tool_usage

    #[test]
    fn test_aggregate_tool_usage() {
        let entries = vec![
            CondensedEntry::tool("Edit", Some("a.rs")),
            CondensedEntry::tool("Edit", Some("b.rs")),
            CondensedEntry::tool("Bash", Some("cargo test")),
            CondensedEntry::tool("Read", Some("c.rs")),
        ];
        let tools = aggregate_tool_usage(&entries);
        assert_eq!(tools.len(), 3);

        let bash = tools.iter().find(|t| t.tool_name == "Bash").unwrap();
        assert_eq!(bash.invocation_count, 1);
        assert!(bash.files_affected.is_empty()); // Bash doesn't modify files

        let edit = tools.iter().find(|t| t.tool_name == "Edit").unwrap();
        assert_eq!(edit.invocation_count, 2);
        assert_eq!(edit.files_affected, vec!["a.rs", "b.rs"]);
    }

    #[test]
    fn test_aggregate_tool_usage_dedup_files() {
        let entries = vec![
            CondensedEntry::tool("Edit", Some("same.rs")),
            CondensedEntry::tool("Edit", Some("same.rs")),
        ];
        let tools = aggregate_tool_usage(&entries);
        let edit = tools.iter().find(|t| t.tool_name == "Edit").unwrap();
        assert_eq!(edit.invocation_count, 2);
        assert_eq!(edit.files_affected, vec!["same.rs"]); // deduplicated
    }

    #[test]
    fn test_aggregate_tool_usage_sorted() {
        let entries = vec![
            CondensedEntry::tool("Zzz", None::<String>),
            CondensedEntry::tool("Aaa", None::<String>),
        ];
        let tools = aggregate_tool_usage(&entries);
        assert_eq!(tools[0].tool_name, "Aaa");
        assert_eq!(tools[1].tool_name, "Zzz");
    }

    // TurnReasoning

    #[test]
    fn test_reasoning_empty() {
        let r = TurnReasoning {
            intent: String::new(),
            outcome: String::new(),
            learnings: Learnings::default(),
            friction: Vec::new(),
            open_items: Vec::new(),
        };
        assert!(r.is_empty());
        assert_eq!(r.learning_count(), 0);
        assert!(!r.has_code_learnings());
    }

    #[test]
    fn test_reasoning_with_content() {
        let r = TurnReasoning {
            intent: "Fix the bug".into(),
            outcome: "Bug fixed".into(),
            learnings: Learnings {
                repo: vec!["Uses RS256".into()],
                code: vec![CodeLearning::new("file.rs", Some(42), "Wrong timezone")],
                workflow: vec!["Use --lib flag".into()],
            },
            friction: vec!["Complex middleware".into()],
            open_items: vec!["Refresh endpoint".into()],
        };
        assert!(!r.is_empty());
        assert_eq!(r.learning_count(), 3);
        assert!(r.has_code_learnings());
    }

    #[test]
    fn test_reasoning_display() {
        let r = TurnReasoning {
            intent: "Fix auth".into(),
            outcome: "Fixed".into(),
            learnings: Learnings {
                repo: vec!["RS256".into()],
                code: vec![],
                workflow: vec![],
            },
            friction: vec![],
            open_items: vec![],
        };
        let display = r.to_string();
        assert!(display.contains("Intent: Fix auth"));
        assert!(display.contains("Outcome: Fixed"));
        assert!(display.contains("RS256"));
    }

    #[test]
    fn test_reasoning_serde_roundtrip() {
        let r = TurnReasoning {
            intent: "intent".into(),
            outcome: "outcome".into(),
            learnings: Learnings {
                repo: vec!["repo learning".into()],
                code: vec![CodeLearning::new("f.rs", Some(1), "finding")
                    .with_function("main")
                    .with_category("bug")],
                workflow: vec!["workflow".into()],
            },
            friction: vec!["friction".into()],
            open_items: vec!["open".into()],
        };
        let json = serde_json::to_string_pretty(&r).unwrap();
        let parsed: TurnReasoning = serde_json::from_str(&json).unwrap();
        assert_eq!(r, parsed);
    }

    // CodeLearning

    #[test]
    fn test_code_learning_minimal() {
        let l = CodeLearning::new("file.rs", Some(42), "Found a bug");
        assert_eq!(l.path, "file.rs");
        assert_eq!(l.line, Some(42));
        assert_eq!(l.finding, "Found a bug");
        assert!(l.function.is_none());
        assert!(l.category.is_none());
        assert!(!l.is_anchored());
    }

    #[test]
    fn test_code_learning_builder() {
        let l = CodeLearning::new("file.rs", Some(42), "Bug")
            .with_function("validate_token")
            .with_end_line(50)
            .with_category("security");
        assert_eq!(l.function.as_deref(), Some("validate_token"));
        assert_eq!(l.end_line, Some(50));
        assert_eq!(l.category.as_deref(), Some("security"));
    }

    #[test]
    fn test_code_learning_display() {
        let l = CodeLearning::new("src/auth.rs", Some(42), "Wrong timezone")
            .with_function("validate_token")
            .with_category("bug");
        let s = l.to_string();
        assert_eq!(s, "src/auth.rs:42 (validate_token) — Wrong timezone [bug]");
    }

    #[test]
    fn test_code_learning_display_range() {
        let l = CodeLearning::new("f.rs", Some(10), "Issue").with_end_line(20);
        assert_eq!(l.to_string(), "f.rs:10-20 — Issue");
    }

    #[test]
    fn test_code_learning_display_no_line() {
        let l = CodeLearning::new("f.rs", None, "General finding");
        assert_eq!(l.to_string(), "f.rs — General finding");
    }

    #[test]
    fn test_code_learning_anchored() {
        let mut l = CodeLearning::new("f.rs", Some(1), "test");
        assert!(!l.is_anchored());

        l._anchor = Some(GraphAnchor {
            trunk: Some((47, 0)),
            branches: vec![(47, 12)],
            leaves: vec![(47, 34)],
        });
        assert!(l.is_anchored());
    }

    #[test]
    fn test_code_learning_serde_with_anchor() {
        let l = CodeLearning {
            path: "f.rs".into(),
            line: Some(42),
            end_line: None,
            function: Some("main".into()),
            finding: "test".into(),
            category: Some("bug".into()),
            _anchor: Some(GraphAnchor {
                trunk: Some((47, 0)),
                branches: vec![(47, 12)],
                leaves: vec![(47, 34), (47, 35)],
            }),
        };
        let json = serde_json::to_string(&l).unwrap();
        let parsed: CodeLearning = serde_json::from_str(&json).unwrap();
        assert_eq!(l, parsed);
        assert!(json.contains("_anchor"));
    }

    #[test]
    fn test_code_learning_serde_without_anchor() {
        let l = CodeLearning::new("f.rs", Some(1), "no anchor");
        let json = serde_json::to_string(&l).unwrap();
        assert!(!json.contains("_anchor")); // skip_serializing_if = None
        let parsed: CodeLearning = serde_json::from_str(&json).unwrap();
        assert_eq!(l, parsed);
        assert!(!parsed.is_anchored());
    }

    // GraphAnchor

    #[test]
    fn test_anchor_empty() {
        let a = GraphAnchor::empty();
        assert!(!a.is_populated());
    }

    #[test]
    fn test_anchor_with_trunk() {
        let a = GraphAnchor {
            trunk: Some((1, 0)),
            branches: vec![],
            leaves: vec![],
        };
        assert!(a.is_populated());
    }

    #[test]
    fn test_anchor_with_all() {
        let a = GraphAnchor {
            trunk: Some((1, 0)),
            branches: vec![(1, 5), (1, 6)],
            leaves: vec![(1, 10), (1, 11), (1, 12)],
        };
        assert!(a.is_populated());
    }

    // ToolUseSummary

    #[test]
    fn test_tool_summary_display() {
        let s = ToolUseSummary::new("Edit", 3, vec!["a.rs".into(), "b.rs".into()]);
        assert_eq!(s.to_string(), "Edit (×3) → a.rs, b.rs");
    }

    #[test]
    fn test_tool_summary_display_no_files() {
        let s = ToolUseSummary::new("Bash", 1, vec![]);
        assert_eq!(s.to_string(), "Bash (×1)");
    }

    // UnhashedTurnData

    #[test]
    fn test_unhashed_new() {
        let entries = vec![
            CondensedEntry::user("Hello"),
            CondensedEntry::tool("Edit", Some("a.rs")),
        ];
        let data = UnhashedTurnData::new("sess-1", 3, "jsonl", entries, &["a.rs".into()]);

        assert_eq!(data.session_id, "sess-1");
        assert_eq!(data.turn_number, 3);
        assert_eq!(data.transcript_format, "jsonl");
        assert_eq!(data.entry_count(), 2);
        assert_eq!(data.prompts, vec!["Hello"]);
        assert_eq!(data.tools_used.len(), 1);
        assert!(!data.has_reasoning());
        assert!(!data.is_redacted());
    }

    #[test]
    fn test_unhashed_with_reasoning() {
        let data =
            UnhashedTurnData::new("s", 1, "jsonl", vec![], &[]).with_reasoning(TurnReasoning {
                intent: "test".into(),
                outcome: "done".into(),
                learnings: Learnings::default(),
                friction: vec![],
                open_items: vec![],
            });
        assert!(data.has_reasoning());
    }

    #[test]
    fn test_unhashed_serde_roundtrip() {
        let entries = vec![
            CondensedEntry::user("prompt"),
            CondensedEntry::assistant("response"),
        ];
        let data = UnhashedTurnData::new("sess-1", 5, "jsonl", entries, &["f.rs".into()])
            .with_reasoning(TurnReasoning {
                intent: "fix".into(),
                outcome: "fixed".into(),
                learnings: Learnings {
                    repo: vec!["pattern".into()],
                    code: vec![CodeLearning::new("f.rs", Some(1), "finding")],
                    workflow: vec![],
                },
                friction: vec!["issue".into()],
                open_items: vec![],
            });

        let json = serde_json::to_string_pretty(&data).unwrap();
        let parsed: UnhashedTurnData = serde_json::from_str(&json).unwrap();
        assert_eq!(data, parsed);
    }

    // Attach / Extract / Strip

    fn make_empty_change() -> atomic_core::change::Change {
        atomic_core::change::Change::empty(atomic_core::change::ChangeHeader::default())
    }

    #[test]
    fn test_attach_and_extract() {
        let mut change = make_empty_change();
        let data = UnhashedTurnData::new("s1", 2, "jsonl", vec![], &[]);

        attach_unhashed(&mut change, &data).unwrap();
        assert!(has_unhashed(&change));

        let extracted = extract_unhashed(&change).unwrap();
        assert_eq!(extracted.session_id, "s1");
        assert_eq!(extracted.turn_number, 2);
    }

    #[test]
    fn test_extract_no_unhashed() {
        let change = make_empty_change();
        assert!(!has_unhashed(&change));
        assert!(extract_unhashed(&change).is_none());
    }

    #[test]
    fn test_strip_unhashed() {
        let mut change = make_empty_change();
        let data = UnhashedTurnData::new(
            "s1",
            1,
            "jsonl",
            vec![CondensedEntry::user("secret prompt")],
            &[],
        )
        .with_reasoning(TurnReasoning {
            intent: "secret intent".into(),
            outcome: "secret outcome".into(),
            learnings: Learnings::default(),
            friction: vec![],
            open_items: vec![],
        });

        attach_unhashed(&mut change, &data).unwrap();
        assert!(has_unhashed(&change));
        assert!(!is_redacted(&change));

        // Strip
        let stripped = strip_unhashed(&mut change);
        assert!(stripped);
        assert!(is_redacted(&change));

        // Verify the stub
        let extracted = extract_unhashed(&change).unwrap();
        assert_eq!(extracted.session_id, "s1");
        assert_eq!(extracted.turn_number, 1);
        assert!(extracted.is_redacted());
        assert!(extracted.condensed_transcript.is_empty());
        assert!(extracted.reasoning.is_none());
        assert!(extracted.prompts.is_empty());
    }

    #[test]
    fn test_strip_no_data_returns_false() {
        let mut change = make_empty_change();
        assert!(!strip_unhashed(&mut change));
    }

    #[test]
    fn test_strip_preserves_hash_conceptually() {
        // The unhashed section doesn't contribute to the change hash.
        // This test verifies that attach/strip doesn't touch the hashed section.
        let mut change = make_empty_change();
        let hash_before = change.hashed.contents_hash;

        let data = UnhashedTurnData::new("s", 1, "jsonl", vec![], &[]);
        attach_unhashed(&mut change, &data).unwrap();
        let hash_after_attach = change.hashed.contents_hash;

        strip_unhashed(&mut change);
        let hash_after_strip = change.hashed.contents_hash;

        assert_eq!(hash_before, hash_after_attach);
        assert_eq!(hash_before, hash_after_strip);
    }

    // Learnings

    #[test]
    fn test_learnings_empty() {
        let l = Learnings::default();
        assert!(l.is_empty());
        assert_eq!(l.total(), 0);
    }

    #[test]
    fn test_learnings_total() {
        let l = Learnings {
            repo: vec!["a".into(), "b".into()],
            code: vec![CodeLearning::new("f", None, "c")],
            workflow: vec!["d".into()],
        };
        assert_eq!(l.total(), 4);
        assert!(!l.is_empty());
    }

    // EntryType

    #[test]
    fn test_entry_type_display() {
        assert_eq!(EntryType::User.to_string(), "User");
        assert_eq!(EntryType::Assistant.to_string(), "Assistant");
        assert_eq!(EntryType::Tool.to_string(), "Tool");
    }

    #[test]
    fn test_entry_type_serde() {
        let json = serde_json::to_string(&EntryType::User).unwrap();
        assert_eq!(json, "\"user\"");
        let parsed: EntryType = serde_json::from_str(&json).unwrap();
        assert_eq!(parsed, EntryType::User);
    }

    // strip_markdown_code_blocks

    #[test]
    fn test_strip_no_blocks() {
        let json = r#"{"intent": "test"}"#;
        assert_eq!(strip_markdown_code_blocks(json), json);
    }

    #[test]
    fn test_strip_json_block() {
        let input = "```json\n{\"intent\": \"test\"}\n```";
        assert_eq!(strip_markdown_code_blocks(input), r#"{"intent": "test"}"#);
    }

    #[test]
    fn test_strip_plain_block() {
        let input = "```\n{\"intent\": \"test\"}\n```";
        assert_eq!(strip_markdown_code_blocks(input), r#"{"intent": "test"}"#);
    }

    #[test]
    fn test_strip_with_whitespace() {
        let input = "  ```json\n  {\"intent\": \"test\"}  \n```  ";
        let result = strip_markdown_code_blocks(input);
        assert!(result.contains("intent"));
    }

    #[test]
    fn test_strip_no_closing() {
        // No closing ``` — return trimmed original
        let input = "```json\n{\"intent\": \"test\"}";
        let result = strip_markdown_code_blocks(input);
        assert!(result.contains("intent"));
    }

    // truncate_for_error

    #[test]
    fn test_truncate_short() {
        assert_eq!(truncate_for_error("hello", 100), "hello");
    }

    #[test]
    fn test_truncate_long() {
        let long = "a".repeat(300);
        let result = truncate_for_error(&long, 50);
        assert!(result.len() <= 54); // 50 + "..."
        assert!(result.ends_with("..."));
    }

    #[test]
    fn test_truncate_exact() {
        let s = "a".repeat(50);
        assert_eq!(truncate_for_error(&s, 50), s);
    }

    // ClaudeCliGenerator construction

    #[test]
    fn test_generator_default() {
        let gen = ClaudeCliGenerator::new();
        assert!(gen.claude_path.is_none());
        assert!(gen.model.is_none());
        assert_eq!(gen.timeout_secs, 60);
        assert_eq!(gen.claude_path(), "claude");
        assert_eq!(gen.model(), "sonnet");
    }

    #[test]
    fn test_generator_with_options() {
        let gen = ClaudeCliGenerator::new()
            .with_claude_path("/usr/local/bin/claude")
            .with_model("opus")
            .with_timeout(120);
        assert_eq!(gen.claude_path(), "/usr/local/bin/claude");
        assert_eq!(gen.model(), "opus");
        assert_eq!(gen.timeout_secs, 120);
    }

    #[test]
    fn test_generator_build_prompt() {
        let gen = ClaudeCliGenerator::new();
        let prompt = gen.build_prompt("[User] Fix the bug\n[Assistant] Done\n");
        assert!(prompt.contains("<transcript>"));
        assert!(prompt.contains("[User] Fix the bug"));
        assert!(prompt.contains("</transcript>"));
        assert!(prompt.contains("Return a JSON object"));
        assert!(prompt.contains("\"function\""));
        assert!(prompt.contains("\"category\""));
    }

    #[test]
    fn test_generator_clean_env_strips_git() {
        // This test verifies the logic, though the actual env vars depend
        // on the test environment
        let env = ClaudeCliGenerator::clean_env();
        for (key, _) in &env {
            assert!(
                !key.starts_with("GIT_"),
                "GIT_ variable should be stripped: {}",
                key
            );
        }
    }

    #[test]
    fn test_generator_debug() {
        let gen = ClaudeCliGenerator::new();
        let debug = format!("{:?}", gen);
        assert!(debug.contains("ClaudeCliGenerator"));
    }

    // MockGenerator

    #[test]
    fn test_mock_generator_success() {
        let reasoning = TurnReasoning {
            intent: "test intent".into(),
            outcome: "test outcome".into(),
            learnings: Learnings::default(),
            friction: vec![],
            open_items: vec![],
        };
        let gen = MockGenerator::success(reasoning.clone());
        let result = gen.generate("transcript", &[]).unwrap();
        assert_eq!(result.intent, "test intent");
        assert_eq!(result.outcome, "test outcome");
    }

    #[test]
    fn test_mock_generator_failure() {
        let gen = MockGenerator::failure("LLM unavailable");
        let result = gen.generate("transcript", &[]);
        assert!(result.is_err());
        assert!(result.unwrap_err().to_string().contains("LLM unavailable"));
    }

    // ReasoningGenerator trait object safety

    #[test]
    fn test_generator_is_object_safe() {
        let reasoning = TurnReasoning {
            intent: "i".into(),
            outcome: "o".into(),
            learnings: Learnings::default(),
            friction: vec![],
            open_items: vec![],
        };
        let gen: Box<dyn ReasoningGenerator> = Box::new(MockGenerator::success(reasoning));
        let result = gen.generate("text", &[]);
        assert!(result.is_ok());
    }

    // try_generate_reasoning (non-fatal wrapper)

    #[test]
    fn test_try_generate_no_claude() {
        // Claude CLI is unlikely to be at this path
        let gen = ClaudeCliGenerator::new().with_claude_path("/nonexistent/claude");
        assert!(!gen.is_available());
    }

    // SUMMARIZATION_PROMPT

    #[test]
    fn test_prompt_has_required_fields() {
        // Verify the prompt asks for all the fields we expect in TurnReasoning
        assert!(SUMMARIZATION_PROMPT.contains("\"intent\""));
        assert!(SUMMARIZATION_PROMPT.contains("\"outcome\""));
        assert!(SUMMARIZATION_PROMPT.contains("\"learnings\""));
        assert!(SUMMARIZATION_PROMPT.contains("\"repo\""));
        assert!(SUMMARIZATION_PROMPT.contains("\"code\""));
        assert!(SUMMARIZATION_PROMPT.contains("\"workflow\""));
        assert!(SUMMARIZATION_PROMPT.contains("\"friction\""));
        assert!(SUMMARIZATION_PROMPT.contains("\"open_items\""));
        assert!(SUMMARIZATION_PROMPT.contains("\"path\""));
        assert!(SUMMARIZATION_PROMPT.contains("\"line\""));
        assert!(SUMMARIZATION_PROMPT.contains("\"function\""));
        assert!(SUMMARIZATION_PROMPT.contains("\"finding\""));
        assert!(SUMMARIZATION_PROMPT.contains("\"category\""));
    }

    #[test]
    fn test_prompt_has_security_boundary() {
        // The transcript should be wrapped in XML tags for injection protection
        assert!(SUMMARIZATION_PROMPT.contains("<transcript>"));
        assert!(SUMMARIZATION_PROMPT.contains("</transcript>"));
    }

    // End-to-end: parse prompt response (simulated)

    #[test]
    fn test_parse_claude_response_format() {
        // Simulate what Claude CLI returns: {"result": "...json..."}
        let reasoning_json = serde_json::json!({
            "intent": "Fix the authentication bug",
            "outcome": "Fixed token validation, tests passing",
            "learnings": {
                "repo": ["Auth uses RS256"],
                "code": [{
                    "path": "src/auth.rs",
                    "line": 42,
                    "function": "validate_token",
                    "finding": "Wrong timezone comparison",
                    "category": "bug"
                }],
                "workflow": ["cargo test --lib is faster"]
            },
            "friction": ["Complex middleware stack"],
            "open_items": ["Refresh endpoint has same bug"]
        });

        let cli_response = serde_json::json!({
            "result": reasoning_json.to_string()
        });

        // Simulate the parsing pipeline
        let result_str = cli_response["result"].as_str().unwrap();
        let clean_json = strip_markdown_code_blocks(result_str);
        let reasoning: TurnReasoning = serde_json::from_str(&clean_json).unwrap();

        assert_eq!(reasoning.intent, "Fix the authentication bug");
        assert_eq!(reasoning.outcome, "Fixed token validation, tests passing");
        assert_eq!(reasoning.learnings.repo, vec!["Auth uses RS256"]);
        assert_eq!(reasoning.learnings.code.len(), 1);
        assert_eq!(reasoning.learnings.code[0].path, "src/auth.rs");
        assert_eq!(reasoning.learnings.code[0].line, Some(42));
        assert_eq!(
            reasoning.learnings.code[0].function.as_deref(),
            Some("validate_token")
        );
        assert_eq!(
            reasoning.learnings.code[0].finding,
            "Wrong timezone comparison"
        );
        assert_eq!(reasoning.learnings.code[0].category.as_deref(), Some("bug"));
        assert_eq!(reasoning.friction, vec!["Complex middleware stack"]);
        assert_eq!(reasoning.open_items, vec!["Refresh endpoint has same bug"]);
    }

    #[test]
    fn test_parse_claude_response_with_markdown_wrapper() {
        // Claude sometimes wraps JSON in markdown despite instructions
        let inner_json = r#"{"intent":"test","outcome":"done","learnings":{"repo":[],"code":[],"workflow":[]},"friction":[],"open_items":[]}"#;
        let wrapped = format!("```json\n{}\n```", inner_json);

        let cli_response = serde_json::json!({
            "result": wrapped
        });

        let result_str = cli_response["result"].as_str().unwrap();
        let clean_json = strip_markdown_code_blocks(result_str);
        let reasoning: TurnReasoning = serde_json::from_str(&clean_json).unwrap();

        assert_eq!(reasoning.intent, "test");
        assert_eq!(reasoning.outcome, "done");
    }

    #[test]
    fn test_parse_claude_response_missing_optional_fields() {
        // LLM might not include all optional fields on CodeLearning
        let json = r#"{
            "intent": "test",
            "outcome": "done",
            "learnings": {
                "repo": [],
                "code": [{"path": "f.rs", "finding": "something"}],
                "workflow": []
            },
            "friction": [],
            "open_items": []
        }"#;

        let reasoning: TurnReasoning = serde_json::from_str(json).unwrap();
        assert_eq!(reasoning.learnings.code.len(), 1);
        assert_eq!(reasoning.learnings.code[0].path, "f.rs");
        assert!(reasoning.learnings.code[0].line.is_none());
        assert!(reasoning.learnings.code[0].function.is_none());
        assert!(reasoning.learnings.code[0].category.is_none());
    }
}
