//! Credit/blame tracking for AI-aware line-level attribution
//!
//! This module provides structures and utilities for tracking who (or what)
//! authored each piece of content in a repository. It's similar to `git blame`
//! but with AI attribution awareness, distinguishing between:
//!
//! - **Human-authored**: Traditional human-written code
//! - **AI-assisted**: Code written with AI help (collaborative)
//! - **AI-generated**: Code primarily generated by AI
//!
//! # Overview
//!
//! The credit system works at multiple granularities:
//!
//! 1. **Change-level**: Each change has an overall attribution (via `Provenance`)
//! 2. **GraphOp-level**: Each graph_op within a change can have its own credit
//! 3. **Line-level**: For display, we can show per-line attribution
//!
//! # Use Cases
//!
//! - **Code review**: Quickly identify AI-generated sections for extra scrutiny
//! - **Compliance**: Track AI usage for licensing/legal requirements
//! - **Analytics**: Understand AI contribution patterns in a codebase
//! - **Debugging**: Know who/what to ask about specific code sections
//!
//! # Example
//!
//! ```rust,ignore
//! use atomic_core::change::{Credit, CreditType, LineCredit};
//!
//! // Create credit for a human author
//! let human_credit = Credit::human("alice", Some("alice@example.com"));
//!
//! // Create credit for AI-assisted code
//! let ai_credit = Credit::ai_assisted(
//!     "bob",
//!     AIVendor::Anthropic,
//!     "claude-sonnet-4",
//!     SuggestionType::Collaborative,
//! );
//!
//! // Get line-level credits for a file
//! let line_credits = get_file_credits(&repo, "src/main.rs")?;
//! for (line_num, credit) in line_credits.iter().enumerate() {
//!     println!("{}: {} - {}", line_num + 1, credit.author_name(), credit.credit_type);
//! }
//! ```
//!
//! # Credit vs Provenance
//!
//! - **Provenance** (in `provenance.rs`): Detailed AI interaction metadata
//!   (tokens, cost, prompts, etc.) stored in the change
//! - **Credit**: Simplified attribution for display and analysis,
//!   derived from Author + Provenance

use super::provenance::{AIVendor, SuggestionType};
use crate::types::Base32;
use crate::Hash;
use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use std::fmt;

/// The type of credit/attribution for a piece of code.
///
/// This categorizes contributions by their human/AI involvement level.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, Serialize, Deserialize, Default)]
#[serde(rename_all = "snake_case")]
pub enum CreditType {
    /// Purely human-authored code with no AI involvement
    #[default]
    Human,

    /// Code where AI provided suggestions that were significantly modified
    ///
    /// The human is the primary author, AI provided assistance.
    AiAssisted,

    /// Code created collaboratively between human and AI
    ///
    /// Both human and AI made substantial contributions.
    Collaborative,

    /// Code primarily generated by AI with minimal human changes
    ///
    /// AI is the primary author, human reviewed/accepted.
    AiGenerated,

    /// Unknown attribution (legacy or missing metadata)
    Unknown,
}

impl CreditType {
    /// Get a human-readable description.
    pub fn description(&self) -> &'static str {
        match self {
            CreditType::Human => "Human",
            CreditType::AiAssisted => "AI-Assisted",
            CreditType::Collaborative => "Human+AI",
            CreditType::AiGenerated => "AI-Generated",
            CreditType::Unknown => "Unknown",
        }
    }

    /// Get a short code for compact display.
    pub fn short_code(&self) -> &'static str {
        match self {
            CreditType::Human => "H",
            CreditType::AiAssisted => "A",
            CreditType::Collaborative => "C",
            CreditType::AiGenerated => "G",
            CreditType::Unknown => "?",
        }
    }

    /// Check if this credit type involves AI.
    #[inline]
    pub fn involves_ai(&self) -> bool {
        matches!(
            self,
            CreditType::AiAssisted | CreditType::Collaborative | CreditType::AiGenerated
        )
    }

    /// Check if this is purely human-authored.
    #[inline]
    pub fn is_human(&self) -> bool {
        matches!(self, CreditType::Human)
    }

    /// Estimate the AI contribution level (0.0 = all human, 1.0 = all AI).
    pub fn ai_contribution_estimate(&self) -> f32 {
        match self {
            CreditType::Human => 0.0,
            CreditType::AiAssisted => 0.3,
            CreditType::Collaborative => 0.5,
            CreditType::AiGenerated => 0.9,
            CreditType::Unknown => 0.0,
        }
    }

    /// Convert from SuggestionType.
    pub fn from_suggestion_type(suggestion_type: SuggestionType) -> Self {
        match suggestion_type {
            SuggestionType::Complete => CreditType::AiGenerated,
            SuggestionType::Partial => CreditType::AiAssisted,
            SuggestionType::Collaborative => CreditType::Collaborative,
            SuggestionType::Selection => CreditType::AiAssisted,
            SuggestionType::Review => CreditType::AiAssisted,
            SuggestionType::Documentation => CreditType::AiGenerated,
            SuggestionType::Debugging => CreditType::Collaborative,
            SuggestionType::Refactoring => CreditType::AiGenerated,
            SuggestionType::Testing => CreditType::AiGenerated,
        }
    }
}

impl fmt::Display for CreditType {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.description())
    }
}

/// Complete credit information for a piece of code.
///
/// This combines author information with AI attribution to provide
/// a complete picture of who/what created a piece of code.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Credit {
    /// The human author's name
    pub author_name: String,

    /// The human author's email (if available)
    #[serde(default)]
    pub author_email: Option<String>,

    /// Type of credit (human, AI-assisted, etc.)
    pub credit_type: CreditType,

    /// AI vendor if AI was involved
    #[serde(default)]
    pub ai_vendor: Option<AIVendor>,

    /// AI model if AI was involved
    #[serde(default)]
    pub ai_model: Option<String>,

    /// The change that introduced this content
    pub change_hash: Hash,

    /// When the content was introduced
    pub timestamp: DateTime<Utc>,

    /// Optional confidence score for AI-generated content (0 to 100, representing percentage)
    /// Stored as integer to allow Eq derivation
    #[serde(default)]
    pub confidence: Option<u8>,
}

impl Credit {
    /// Create credit for purely human-authored content.
    pub fn human(
        name: impl Into<String>,
        email: Option<impl Into<String>>,
        change_hash: Hash,
        timestamp: DateTime<Utc>,
    ) -> Self {
        Self {
            author_name: name.into(),
            author_email: email.map(Into::into),
            credit_type: CreditType::Human,
            ai_vendor: None,
            ai_model: None,
            change_hash,
            timestamp,
            confidence: None,
        }
    }

    /// Create credit for AI-assisted content.
    pub fn ai_assisted(
        author_name: impl Into<String>,
        author_email: Option<impl Into<String>>,
        vendor: AIVendor,
        model: impl Into<String>,
        change_hash: Hash,
        timestamp: DateTime<Utc>,
    ) -> Self {
        Self {
            author_name: author_name.into(),
            author_email: author_email.map(Into::into),
            credit_type: CreditType::AiAssisted,
            ai_vendor: Some(vendor),
            ai_model: Some(model.into()),
            change_hash,
            timestamp,
            confidence: None,
        }
    }

    /// Create credit for AI-generated content.
    pub fn ai_generated(
        author_name: impl Into<String>,
        author_email: Option<impl Into<String>>,
        vendor: AIVendor,
        model: impl Into<String>,
        change_hash: Hash,
        timestamp: DateTime<Utc>,
        confidence: Option<f32>,
    ) -> Self {
        Self {
            author_name: author_name.into(),
            author_email: author_email.map(Into::into),
            credit_type: CreditType::AiGenerated,
            ai_vendor: Some(vendor),
            ai_model: Some(model.into()),
            change_hash,
            timestamp,
            confidence: confidence.map(|c| (c.clamp(0.0, 1.0) * 100.0) as u8),
        }
    }

    /// Create credit for collaborative human+AI content.
    pub fn collaborative(
        author_name: impl Into<String>,
        author_email: Option<impl Into<String>>,
        vendor: AIVendor,
        model: impl Into<String>,
        change_hash: Hash,
        timestamp: DateTime<Utc>,
    ) -> Self {
        Self {
            author_name: author_name.into(),
            author_email: author_email.map(Into::into),
            credit_type: CreditType::Collaborative,
            ai_vendor: Some(vendor),
            ai_model: Some(model.into()),
            change_hash,
            timestamp,
            confidence: None,
        }
    }

    /// Create credit with unknown attribution.
    pub fn unknown(change_hash: Hash, timestamp: DateTime<Utc>) -> Self {
        Self {
            author_name: "Unknown".to_string(),
            author_email: None,
            credit_type: CreditType::Unknown,
            ai_vendor: None,
            ai_model: None,
            change_hash,
            timestamp,
            confidence: None,
        }
    }

    /// Set the confidence level (0.0 to 1.0, stored as 0-100).
    pub fn with_confidence(mut self, confidence: f32) -> Self {
        self.confidence = Some((confidence.clamp(0.0, 1.0) * 100.0) as u8);
        self
    }

    /// Get the confidence as a float (0.0 to 1.0).
    pub fn confidence_float(&self) -> Option<f32> {
        self.confidence.map(|c| c as f32 / 100.0)
    }

    /// Get a display string for the author.
    pub fn author_display(&self) -> String {
        match &self.author_email {
            Some(email) => format!("{} <{}>", self.author_name, email),
            None => self.author_name.clone(),
        }
    }

    /// Get a short attribution string (e.g., "alice [H]" or "bob [A:claude]").
    pub fn short_attribution(&self) -> String {
        let type_code = self.credit_type.short_code();
        match (&self.ai_vendor, &self.ai_model) {
            (Some(vendor), Some(model)) => {
                // Truncate model name for display
                let short_model = if model.len() > 10 {
                    &model[..10]
                } else {
                    model
                };
                format!(
                    "{} [{}:{}:{}]",
                    self.author_name,
                    type_code,
                    vendor.name(),
                    short_model
                )
            }
            (Some(vendor), None) => {
                format!("{} [{}:{}]", self.author_name, type_code, vendor.name())
            }
            _ => format!("{} [{}]", self.author_name, type_code),
        }
    }

    /// Check if AI was involved.
    #[inline]
    pub fn involves_ai(&self) -> bool {
        self.credit_type.involves_ai()
    }

    /// Get the AI contribution estimate.
    pub fn ai_contribution(&self) -> f32 {
        self.credit_type.ai_contribution_estimate()
    }
}

impl fmt::Display for Credit {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.short_attribution())
    }
}

/// Credit information for a single line.
///
/// This is used when displaying blame/credit information for a file.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LineCredit {
    /// Line number (1-indexed)
    pub line_number: u64,

    /// The credit for this line
    pub credit: Credit,

    /// The actual line content (optional, for display)
    #[serde(default)]
    pub content: Option<String>,
}

impl LineCredit {
    /// Create a new line credit.
    pub fn new(line_number: u64, credit: Credit) -> Self {
        Self {
            line_number,
            credit,
            content: None,
        }
    }

    /// Create a line credit with content.
    pub fn with_content(line_number: u64, credit: Credit, content: impl Into<String>) -> Self {
        Self {
            line_number,
            credit,
            content: Some(content.into()),
        }
    }

    /// Format for blame-style output.
    ///
    /// Returns a string like:
    /// `abc123 (alice [H] 2024-01-15)  42: let x = 1;`
    pub fn format_blame(&self) -> String {
        let hash_short = &self.credit.change_hash.to_base32()[..8];
        let date = self.credit.timestamp.format("%Y-%m-%d");
        let attribution = self.credit.short_attribution();

        match &self.content {
            Some(content) => {
                format!(
                    "{} ({} {}) {:>4}: {}",
                    hash_short, attribution, date, self.line_number, content
                )
            }
            None => {
                format!(
                    "{} ({} {}) {:>4}:",
                    hash_short, attribution, date, self.line_number
                )
            }
        }
    }
}

impl fmt::Display for LineCredit {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.format_blame())
    }
}

/// Statistics about credits in a file or repository.
///
/// This provides aggregate information about attribution.
#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
pub struct CreditStats {
    /// Total number of lines
    pub total_lines: u64,

    /// Lines authored by humans only
    pub human_lines: u64,

    /// Lines with AI assistance
    pub ai_assisted_lines: u64,

    /// Lines created collaboratively
    pub collaborative_lines: u64,

    /// Lines primarily AI-generated
    pub ai_generated_lines: u64,

    /// Lines with unknown attribution
    pub unknown_lines: u64,

    /// Unique human authors
    pub unique_authors: u64,

    /// Unique AI models used
    pub unique_ai_models: u64,

    /// AI vendors used (by name)
    #[serde(default)]
    pub ai_vendors: Vec<String>,
}

impl CreditStats {
    /// Create empty stats.
    pub fn new() -> Self {
        Self::default()
    }

    /// Add a credit to the statistics.
    pub fn add(&mut self, credit: &Credit) {
        self.total_lines += 1;

        match credit.credit_type {
            CreditType::Human => self.human_lines += 1,
            CreditType::AiAssisted => self.ai_assisted_lines += 1,
            CreditType::Collaborative => self.collaborative_lines += 1,
            CreditType::AiGenerated => self.ai_generated_lines += 1,
            CreditType::Unknown => self.unknown_lines += 1,
        }

        if let Some(ref vendor) = credit.ai_vendor {
            let vendor_name = vendor.name().to_string();
            if !self.ai_vendors.contains(&vendor_name) {
                self.ai_vendors.push(vendor_name);
            }
        }
    }

    /// Get the percentage of lines involving AI.
    pub fn ai_percentage(&self) -> f64 {
        if self.total_lines == 0 {
            return 0.0;
        }
        let ai_lines = self.ai_assisted_lines + self.collaborative_lines + self.ai_generated_lines;
        (ai_lines as f64 / self.total_lines as f64) * 100.0
    }

    /// Get the percentage of purely human lines.
    pub fn human_percentage(&self) -> f64 {
        if self.total_lines == 0 {
            return 0.0;
        }
        (self.human_lines as f64 / self.total_lines as f64) * 100.0
    }

    /// Get a summary string.
    pub fn summary(&self) -> String {
        format!(
            "{} lines: {:.1}% human, {:.1}% AI-involved ({} AI-assisted, {} collaborative, {} AI-generated)",
            self.total_lines,
            self.human_percentage(),
            self.ai_percentage(),
            self.ai_assisted_lines,
            self.collaborative_lines,
            self.ai_generated_lines
        )
    }

    /// Merge another stats into this one.
    pub fn merge(&mut self, other: &CreditStats) {
        self.total_lines += other.total_lines;
        self.human_lines += other.human_lines;
        self.ai_assisted_lines += other.ai_assisted_lines;
        self.collaborative_lines += other.collaborative_lines;
        self.ai_generated_lines += other.ai_generated_lines;
        self.unknown_lines += other.unknown_lines;

        for vendor in &other.ai_vendors {
            if !self.ai_vendors.contains(vendor) {
                self.ai_vendors.push(vendor.clone());
            }
        }
    }
}

impl fmt::Display for CreditStats {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.summary())
    }
}

/// A range of lines with the same credit.
///
/// This is more efficient than storing per-line credits when
/// consecutive lines have the same attribution.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreditRange {
    /// Start line (1-indexed, inclusive)
    pub start_line: u64,

    /// End line (1-indexed, inclusive)
    pub end_line: u64,

    /// The credit for this range
    pub credit: Credit,
}

impl CreditRange {
    /// Create a new credit range.
    pub fn new(start_line: u64, end_line: u64, credit: Credit) -> Self {
        Self {
            start_line,
            end_line,
            credit,
        }
    }

    /// Create a single-line range.
    pub fn single(line: u64, credit: Credit) -> Self {
        Self::new(line, line, credit)
    }

    /// Get the number of lines in this range.
    pub fn line_count(&self) -> u64 {
        self.end_line - self.start_line + 1
    }

    /// Check if a line number is in this range.
    pub fn contains(&self, line: u64) -> bool {
        line >= self.start_line && line <= self.end_line
    }

    /// Try to extend this range with another credit.
    ///
    /// Returns true if the extension was successful (credits match and lines are adjacent).
    pub fn try_extend(&mut self, line: u64, credit: &Credit) -> bool {
        if line == self.end_line + 1 && self.credit == *credit {
            self.end_line = line;
            true
        } else {
            false
        }
    }
}

impl fmt::Display for CreditRange {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        if self.start_line == self.end_line {
            write!(f, "L{}: {}", self.start_line, self.credit)
        } else {
            write!(f, "L{}-{}: {}", self.start_line, self.end_line, self.credit)
        }
    }
}

/// Collection of credit ranges for a file.
///
/// This provides an efficient representation of credits for an entire file,
/// using ranges to avoid per-line overhead when consecutive lines have the
/// same attribution.
#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
pub struct FileCredits {
    /// The file path
    pub path: String,

    /// Credit ranges (in line order)
    pub ranges: Vec<CreditRange>,

    /// Cached statistics
    #[serde(skip)]
    stats_cache: Option<CreditStats>,
}

impl FileCredits {
    /// Create empty file credits.
    pub fn new(path: impl Into<String>) -> Self {
        Self {
            path: path.into(),
            ranges: Vec::new(),
            stats_cache: None,
        }
    }

    /// Add a line credit (will merge with adjacent ranges if possible).
    pub fn add_line(&mut self, line: u64, credit: Credit) {
        self.stats_cache = None; // Invalidate cache

        // Try to extend the last range
        if let Some(last) = self.ranges.last_mut() {
            if last.try_extend(line, &credit) {
                return;
            }
        }

        // Create new range
        self.ranges.push(CreditRange::single(line, credit));
    }

    /// Add a range of lines with the same credit.
    pub fn add_range(&mut self, start: u64, end: u64, credit: Credit) {
        self.stats_cache = None;
        self.ranges.push(CreditRange::new(start, end, credit));
    }

    /// Get the credit for a specific line.
    pub fn get_credit(&self, line: u64) -> Option<&Credit> {
        self.ranges
            .iter()
            .find(|r| r.contains(line))
            .map(|r| &r.credit)
    }

    /// Get statistics for this file.
    pub fn stats(&self) -> CreditStats {
        let mut stats = CreditStats::new();
        for range in &self.ranges {
            for _ in 0..range.line_count() {
                stats.add(&range.credit);
            }
        }
        stats
    }

    /// Get the total line count.
    pub fn total_lines(&self) -> u64 {
        self.ranges.iter().map(|r| r.line_count()).sum()
    }

    /// Check if the file has any AI-involved content.
    pub fn has_ai_content(&self) -> bool {
        self.ranges.iter().any(|r| r.credit.involves_ai())
    }

    /// Get all ranges involving AI.
    pub fn ai_ranges(&self) -> Vec<&CreditRange> {
        self.ranges
            .iter()
            .filter(|r| r.credit.involves_ai())
            .collect()
    }

    /// Get all ranges that are purely human.
    pub fn human_ranges(&self) -> Vec<&CreditRange> {
        self.ranges
            .iter()
            .filter(|r| r.credit.credit_type.is_human())
            .collect()
    }

    /// Iterate over all lines with their credits.
    pub fn iter_lines(&self) -> impl Iterator<Item = (u64, &Credit)> {
        self.ranges
            .iter()
            .flat_map(|r| (r.start_line..=r.end_line).map(move |line| (line, &r.credit)))
    }
}

impl fmt::Display for FileCredits {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        writeln!(f, "Credits for {}:", self.path)?;
        for range in &self.ranges {
            writeln!(f, "  {}", range)?;
        }
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::types::Base32;

    fn test_hash() -> Hash {
        Hash::of(b"test change")
    }

    fn test_timestamp() -> DateTime<Utc> {
        chrono::DateTime::parse_from_rfc3339("2024-01-15T10:30:00Z")
            .unwrap()
            .with_timezone(&Utc)
    }

    // CreditType Tests

    #[test]
    fn test_credit_type_descriptions() {
        assert_eq!(CreditType::Human.description(), "Human");
        assert_eq!(CreditType::AiAssisted.description(), "AI-Assisted");
        assert_eq!(CreditType::Collaborative.description(), "Human+AI");
        assert_eq!(CreditType::AiGenerated.description(), "AI-Generated");
    }

    #[test]
    fn test_credit_type_short_codes() {
        assert_eq!(CreditType::Human.short_code(), "H");
        assert_eq!(CreditType::AiAssisted.short_code(), "A");
        assert_eq!(CreditType::Collaborative.short_code(), "C");
        assert_eq!(CreditType::AiGenerated.short_code(), "G");
    }

    #[test]
    fn test_credit_type_involves_ai() {
        assert!(!CreditType::Human.involves_ai());
        assert!(CreditType::AiAssisted.involves_ai());
        assert!(CreditType::Collaborative.involves_ai());
        assert!(CreditType::AiGenerated.involves_ai());
        assert!(!CreditType::Unknown.involves_ai());
    }

    #[test]
    fn test_credit_type_ai_contribution() {
        assert_eq!(CreditType::Human.ai_contribution_estimate(), 0.0);
        assert!(CreditType::AiAssisted.ai_contribution_estimate() > 0.0);
        assert!(CreditType::AiAssisted.ai_contribution_estimate() < 0.5);
        assert_eq!(CreditType::Collaborative.ai_contribution_estimate(), 0.5);
        assert!(CreditType::AiGenerated.ai_contribution_estimate() > 0.5);
    }

    #[test]
    fn test_credit_type_from_suggestion() {
        assert_eq!(
            CreditType::from_suggestion_type(SuggestionType::Complete),
            CreditType::AiGenerated
        );
        assert_eq!(
            CreditType::from_suggestion_type(SuggestionType::Partial),
            CreditType::AiAssisted
        );
        assert_eq!(
            CreditType::from_suggestion_type(SuggestionType::Collaborative),
            CreditType::Collaborative
        );
    }

    #[test]
    fn test_credit_type_default() {
        assert_eq!(CreditType::default(), CreditType::Human);
    }

    // Credit Tests

    #[test]
    fn test_credit_human() {
        let credit = Credit::human(
            "alice",
            Some("alice@example.com"),
            test_hash(),
            test_timestamp(),
        );

        assert_eq!(credit.author_name, "alice");
        assert_eq!(credit.author_email, Some("alice@example.com".to_string()));
        assert_eq!(credit.credit_type, CreditType::Human);
        assert!(credit.ai_vendor.is_none());
        assert!(!credit.involves_ai());
    }

    #[test]
    fn test_credit_ai_assisted() {
        let credit = Credit::ai_assisted(
            "bob",
            None::<String>,
            AIVendor::Anthropic,
            "claude-sonnet-4",
            test_hash(),
            test_timestamp(),
        );

        assert_eq!(credit.author_name, "bob");
        assert_eq!(credit.credit_type, CreditType::AiAssisted);
        assert_eq!(credit.ai_vendor, Some(AIVendor::Anthropic));
        assert_eq!(credit.ai_model, Some("claude-sonnet-4".to_string()));
        assert!(credit.involves_ai());
    }

    #[test]
    fn test_credit_ai_generated() {
        let credit = Credit::ai_generated(
            "carol",
            Some("carol@example.com"),
            AIVendor::OpenAI,
            "gpt-4o",
            test_hash(),
            test_timestamp(),
            Some(0.95),
        );

        assert_eq!(credit.credit_type, CreditType::AiGenerated);
        assert_eq!(credit.confidence, Some(95)); // 0.95 * 100
    }

    #[test]
    fn test_credit_author_display() {
        let with_email = Credit::human(
            "alice",
            Some("alice@example.com"),
            test_hash(),
            test_timestamp(),
        );
        assert_eq!(with_email.author_display(), "alice <alice@example.com>");

        let without_email = Credit::human("bob", None::<String>, test_hash(), test_timestamp());
        assert_eq!(without_email.author_display(), "bob");
    }

    #[test]
    fn test_credit_short_attribution() {
        let human = Credit::human("alice", None::<String>, test_hash(), test_timestamp());
        assert_eq!(human.short_attribution(), "alice [H]");

        let ai = Credit::ai_assisted(
            "bob",
            None::<String>,
            AIVendor::Anthropic,
            "claude",
            test_hash(),
            test_timestamp(),
        );
        assert!(ai.short_attribution().contains("[A:anthropic:claude]"));
    }

    #[test]
    fn test_credit_with_confidence() {
        let credit = Credit::human("alice", None::<String>, test_hash(), test_timestamp())
            .with_confidence(0.8);
        assert_eq!(credit.confidence, Some(80)); // 0.8 * 100

        // Test clamping
        let high = Credit::human("bob", None::<String>, test_hash(), test_timestamp())
            .with_confidence(1.5);
        assert_eq!(high.confidence, Some(100)); // clamped to 1.0 * 100

        let low = Credit::human("carol", None::<String>, test_hash(), test_timestamp())
            .with_confidence(-0.5);
        assert_eq!(low.confidence, Some(0)); // clamped to 0.0 * 100
    }

    #[test]
    fn test_credit_json_roundtrip() {
        let credit = Credit::ai_assisted(
            "alice",
            Some("alice@example.com"),
            AIVendor::Anthropic,
            "claude-sonnet-4",
            test_hash(),
            test_timestamp(),
        );

        let json = serde_json::to_string(&credit).unwrap();
        let parsed: Credit = serde_json::from_str(&json).unwrap();
        assert_eq!(credit, parsed);
    }

    // LineCredit Tests

    #[test]
    fn test_line_credit_new() {
        let credit = Credit::human("alice", None::<String>, test_hash(), test_timestamp());
        let line_credit = LineCredit::new(42, credit);

        assert_eq!(line_credit.line_number, 42);
        assert_eq!(line_credit.content, None);
    }

    #[test]
    fn test_line_credit_with_content() {
        let credit = Credit::human("alice", None::<String>, test_hash(), test_timestamp());
        let line_credit = LineCredit::with_content(10, credit, "let x = 42;");

        assert_eq!(line_credit.line_number, 10);
        assert_eq!(line_credit.content, Some("let x = 42;".to_string()));
    }

    #[test]
    fn test_line_credit_format_blame() {
        let credit = Credit::human("alice", None::<String>, test_hash(), test_timestamp());
        let line_credit = LineCredit::with_content(42, credit, "let x = 1;");

        let blame = line_credit.format_blame();
        assert!(blame.contains("alice"));
        assert!(blame.contains("[H]"));
        assert!(blame.contains("42"));
        assert!(blame.contains("let x = 1;"));
    }

    // CreditStats Tests

    #[test]
    fn test_credit_stats_new() {
        let stats = CreditStats::new();
        assert_eq!(stats.total_lines, 0);
        assert_eq!(stats.human_lines, 0);
    }

    #[test]
    fn test_credit_stats_add() {
        let mut stats = CreditStats::new();

        let human = Credit::human("alice", None::<String>, test_hash(), test_timestamp());
        stats.add(&human);
        stats.add(&human);

        let ai = Credit::ai_generated(
            "bob",
            None::<String>,
            AIVendor::Anthropic,
            "claude",
            test_hash(),
            test_timestamp(),
            None,
        );
        stats.add(&ai);

        assert_eq!(stats.total_lines, 3);
        assert_eq!(stats.human_lines, 2);
        assert_eq!(stats.ai_generated_lines, 1);
    }

    #[test]
    fn test_credit_stats_percentages() {
        let mut stats = CreditStats::new();

        for _ in 0..7 {
            stats.add(&Credit::human(
                "alice",
                None::<String>,
                test_hash(),
                test_timestamp(),
            ));
        }
        for _ in 0..3 {
            stats.add(&Credit::ai_generated(
                "bob",
                None::<String>,
                AIVendor::Anthropic,
                "claude",
                test_hash(),
                test_timestamp(),
                None,
            ));
        }

        assert!((stats.human_percentage() - 70.0).abs() < 0.1);
        assert!((stats.ai_percentage() - 30.0).abs() < 0.1);
    }

    #[test]
    fn test_credit_stats_merge() {
        let mut stats1 = CreditStats::new();
        stats1.add(&Credit::human(
            "alice",
            None::<String>,
            test_hash(),
            test_timestamp(),
        ));

        let mut stats2 = CreditStats::new();
        stats2.add(&Credit::ai_generated(
            "bob",
            None::<String>,
            AIVendor::OpenAI,
            "gpt-4",
            test_hash(),
            test_timestamp(),
            None,
        ));

        stats1.merge(&stats2);
        assert_eq!(stats1.total_lines, 2);
        assert_eq!(stats1.human_lines, 1);
        assert_eq!(stats1.ai_generated_lines, 1);
    }

    // CreditRange Tests

    #[test]
    fn test_credit_range_single() {
        let credit = Credit::human("alice", None::<String>, test_hash(), test_timestamp());
        let range = CreditRange::single(42, credit);

        assert_eq!(range.start_line, 42);
        assert_eq!(range.end_line, 42);
        assert_eq!(range.line_count(), 1);
    }

    #[test]
    fn test_credit_range_contains() {
        let credit = Credit::human("alice", None::<String>, test_hash(), test_timestamp());
        let range = CreditRange::new(10, 20, credit);

        assert!(!range.contains(9));
        assert!(range.contains(10));
        assert!(range.contains(15));
        assert!(range.contains(20));
        assert!(!range.contains(21));
    }

    #[test]
    fn test_credit_range_try_extend() {
        let credit = Credit::human("alice", None::<String>, test_hash(), test_timestamp());
        let mut range = CreditRange::new(10, 15, credit.clone());

        // Should extend with same credit and adjacent line
        assert!(range.try_extend(16, &credit));
        assert_eq!(range.end_line, 16);

        // Should not extend with non-adjacent line
        assert!(!range.try_extend(18, &credit));

        // Should not extend with different credit
        let other = Credit::ai_generated(
            "bob",
            None::<String>,
            AIVendor::Anthropic,
            "claude",
            test_hash(),
            test_timestamp(),
            None,
        );
        assert!(!range.try_extend(17, &other));
    }

    // FileCredits Tests

    #[test]
    fn test_file_credits_new() {
        let fc = FileCredits::new("src/main.rs");
        assert_eq!(fc.path, "src/main.rs");
        assert!(fc.ranges.is_empty());
    }

    #[test]
    fn test_file_credits_add_line() {
        let mut fc = FileCredits::new("test.rs");
        let credit = Credit::human("alice", None::<String>, test_hash(), test_timestamp());

        fc.add_line(1, credit.clone());
        fc.add_line(2, credit.clone());
        fc.add_line(3, credit.clone());

        // Should be merged into one range
        assert_eq!(fc.ranges.len(), 1);
        assert_eq!(fc.ranges[0].start_line, 1);
        assert_eq!(fc.ranges[0].end_line, 3);
    }

    #[test]
    fn test_file_credits_mixed() {
        let mut fc = FileCredits::new("test.rs");
        let human = Credit::human("alice", None::<String>, test_hash(), test_timestamp());
        let ai = Credit::ai_generated(
            "bob",
            None::<String>,
            AIVendor::Anthropic,
            "claude",
            test_hash(),
            test_timestamp(),
            None,
        );

        fc.add_line(1, human.clone());
        fc.add_line(2, human.clone());
        fc.add_line(3, ai.clone());
        fc.add_line(4, ai.clone());
        fc.add_line(5, human.clone());

        // Should have 3 ranges: human(1-2), ai(3-4), human(5)
        assert_eq!(fc.ranges.len(), 3);
        assert!(fc.has_ai_content());
    }

    #[test]
    fn test_file_credits_get_credit() {
        let mut fc = FileCredits::new("test.rs");
        let human = Credit::human("alice", None::<String>, test_hash(), test_timestamp());

        fc.add_line(1, human.clone());
        fc.add_line(2, human.clone());

        assert!(fc.get_credit(1).is_some());
        assert!(fc.get_credit(2).is_some());
        assert!(fc.get_credit(3).is_none());
    }

    #[test]
    fn test_file_credits_stats() {
        let mut fc = FileCredits::new("test.rs");
        let human = Credit::human("alice", None::<String>, test_hash(), test_timestamp());
        let ai = Credit::ai_generated(
            "bob",
            None::<String>,
            AIVendor::Anthropic,
            "claude",
            test_hash(),
            test_timestamp(),
            None,
        );

        for i in 1..=7 {
            fc.add_line(i, human.clone());
        }
        for i in 8..=10 {
            fc.add_line(i, ai.clone());
        }

        let stats = fc.stats();
        assert_eq!(stats.total_lines, 10);
        assert_eq!(stats.human_lines, 7);
        assert_eq!(stats.ai_generated_lines, 3);
    }

    #[test]
    fn test_file_credits_ai_ranges() {
        let mut fc = FileCredits::new("test.rs");
        let human = Credit::human("alice", None::<String>, test_hash(), test_timestamp());
        let ai = Credit::ai_generated(
            "bob",
            None::<String>,
            AIVendor::Anthropic,
            "claude",
            test_hash(),
            test_timestamp(),
            None,
        );

        fc.add_line(1, human.clone());
        fc.add_line(2, ai.clone());
        fc.add_line(3, ai.clone());
        fc.add_line(4, human.clone());

        let ai_ranges = fc.ai_ranges();
        assert_eq!(ai_ranges.len(), 1);
        assert_eq!(ai_ranges[0].start_line, 2);
        assert_eq!(ai_ranges[0].end_line, 3);
    }

    #[test]
    fn test_file_credits_iter_lines() {
        let mut fc = FileCredits::new("test.rs");
        let credit = Credit::human("alice", None::<String>, test_hash(), test_timestamp());

        fc.add_line(1, credit.clone());
        fc.add_line(2, credit.clone());
        fc.add_line(3, credit.clone());

        let lines: Vec<_> = fc.iter_lines().collect();
        assert_eq!(lines.len(), 3);
        assert_eq!(lines[0].0, 1);
        assert_eq!(lines[1].0, 2);
        assert_eq!(lines[2].0, 3);
    }
}
