//! Predicate vocabulary for the vault knowledge graph.
//!
//! Defines standard ontology prefixes and predicates used in the triple store.
//! Based on W3C PROV-O, SKOS, Dublin Core, and vault-specific relations.

/// Ontology prefix constants.
pub mod prefix {
    /// Atomic's canonical domain ontology.
    pub const ATOM: &str = "atom";
    /// W3C Provenance Ontology — who did what, when, using what.
    pub const PROV: &str = "prov";
    /// Simple Knowledge Organization System — concepts, hierarchies.
    pub const SKOS: &str = "skos";
    /// Dublin Core — document metadata.
    pub const DC: &str = "dc";
    /// Vault-specific relations.
    pub const VAULT: &str = "vault";
    /// RDF type.
    pub const RDF: &str = "rdf";
}

/// Standard predicates used in the vault triple store.
pub mod predicate {
    // ── PROV-O (Provenance) ──────────────────────────────────────
    /// An entity was associated with an agent (e.g., session → developer).
    pub const WAS_ASSOCIATED_WITH: &str = "prov:wasAssociatedWith";
    /// An entity used another entity (e.g., session → file).
    pub const USED: &str = "prov:used";
    /// An entity was generated by an activity (e.g., file → session).
    pub const WAS_GENERATED_BY: &str = "prov:wasGeneratedBy";
    /// An activity was informed by another activity.
    pub const WAS_INFORMED_BY: &str = "prov:wasInformedBy";
    /// An entity was derived from another entity.
    pub const WAS_DERIVED_FROM: &str = "prov:wasDerivedFrom";
    /// An Atomic Intent was informed by a Memory.
    pub const INFORMED_BY: &str = "atom:informedBy";
    /// An activity executed a plan (e.g., session turn → vault intent).
    pub const HAD_PLAN: &str = "prov:hadPlan";
    /// A collection contains a member (e.g., session → session turn).
    pub const HAD_MEMBER: &str = "prov:hadMember";
    /// An activity generated an entity (e.g., session turn → change).
    pub const GENERATED: &str = "prov:generated";

    // ── SKOS (Knowledge Organization) ────────────────────────────
    /// Broader concept (e.g., "authentication" → "security").
    pub const BROADER: &str = "skos:broader";
    /// Narrower concept (e.g., "security" → "authentication").
    pub const NARROWER: &str = "skos:narrower";
    /// Subject/topic (e.g., intent → concept).
    pub const SUBJECT: &str = "skos:subject";
    /// Related concept (non-hierarchical).
    pub const RELATED: &str = "skos:related";

    // ── Dublin Core (Metadata) ───────────────────────────────────
    /// Resource type (e.g., "goal", "intent", "memory").
    pub const TYPE: &str = "dc:type";
    /// Creator of the resource.
    pub const CREATOR: &str = "dc:creator";
    /// Date of creation/modification.
    pub const DATE: &str = "dc:date";
    /// Human-readable description.
    pub const DESCRIPTION: &str = "dc:description";

    // ── RDF ──────────────────────────────────────────────────────
    /// Type assertion (e.g., session:abc rdf:type vault:Goal).
    pub const RDF_TYPE: &str = "rdf:type";

    // ── Vault-specific ──────────────────────────────────────────
    /// Intent blocks another intent.
    pub const BLOCKS: &str = "vault:blocks";
    /// Intent is blocked by another intent.
    pub const BLOCKED_BY: &str = "vault:blockedBy";
    /// Current status of an entity.
    pub const STATUS: &str = "vault:status";
    /// Entity is assigned to a person/agent.
    pub const ASSIGNED_TO: &str = "vault:assignedTo";
    /// Entity links to an intent.
    pub const LINKED_INTENT: &str = "vault:linkedIntent";
    /// Entity links to a goal.
    pub const LINKED_GOAL: &str = "vault:linkedGoal";
    /// Entity references another entity (wiki-link style).
    pub const REFERENCES: &str = "vault:references";
    /// Entity applies to a concept/domain.
    pub const APPLIES_TO: &str = "vault:appliesTo";
    /// Entity has a label/tag.
    pub const HAS_LABEL: &str = "vault:hasLabel";
    /// Entity has priority.
    pub const PRIORITY: &str = "vault:priority";
    /// A session turn is explained by a provenance graph.
    pub const EXPLAINED_BY: &str = "vault:explainedBy";
    /// A session turn produced a todo snapshot (status in edge metadata).
    pub const HAS_TODO: &str = "vault:hasTodo";
}

/// Vault entity type constants (used as objects with `rdf:type`).
pub mod entity_type {
    pub const GOAL: &str = "vault:Goal";
    pub const INTENT: &str = "vault:Intent";
    pub const MEMORY: &str = "vault:Memory";
    pub const SKILL: &str = "vault:Skill";
    pub const TOOL_RESULT: &str = "vault:ToolResult";
    pub const FILE: &str = "vault:File";
    pub const IDENTITY: &str = "vault:Identity";
    pub const CONCEPT: &str = "vault:Concept";
    /// An agent session (one ledger).
    pub const SESSION: &str = "vault:Session";
    /// One turn row in a session ledger.
    pub const SESSION_TURN: &str = "vault:SessionTurn";
    /// A todo item tracked by an intent or snapshotted by a turn.
    pub const TODO: &str = "vault:Todo";
    /// A content-addressed provenance graph explaining turn(s)/change(s).
    pub const PROVENANCE: &str = "vault:ProvenanceGraph";
}

/// Edge kinds used in the knowledge graph.
///
/// These match the atomic-enterprise KG model for compatibility.
pub mod edge_kind {
    /// Change modifies a file.
    pub const MODIFIES: &str = "MODIFIES";
    /// Entity defines a symbol (function, class, etc.).
    pub const DEFINES: &str = "DEFINES";
    /// Change depends on another change.
    pub const DEPENDS_ON: &str = "DEPENDS_ON";
    /// Entity/change belongs to a view.
    pub const ON_VIEW: &str = "ON_VIEW";
    /// View is a child of another view (parent chain).
    pub const CHILD_OF: &str = "CHILD_OF";
    /// Change is visible from a view.
    pub const VISIBLE_FROM: &str = "VISIBLE_FROM";
    /// Entity calls another entity.
    pub const CALLS: &str = "CALLS";
    /// File imports from another file.
    pub const IMPORTS: &str = "IMPORTS";
    /// File exports a symbol.
    pub const EXPORTS: &str = "EXPORTS";
    /// Entity references another entity.
    pub const REFERENCES: &str = "REFERENCES";
    /// Goal is linked to an intent.
    pub const LINKED_INTENT: &str = "LINKED_INTENT";
    /// Goal is linked to another goal.
    pub const LINKED_GOAL: &str = "LINKED_GOAL";
    /// Entity is assigned to an identity.
    pub const ASSIGNED_TO: &str = "ASSIGNED_TO";
    /// Intent blocks another intent.
    pub const BLOCKS: &str = "BLOCKS";
    /// Intent is blocked by another intent.
    pub const BLOCKED_BY: &str = "BLOCKED_BY";
    /// Goal/intent was authored by an identity.
    pub const AUTHORED_BY: &str = "AUTHORED_BY";
    /// Entity has a tag/label.
    pub const HAS_LABEL: &str = "HAS_LABEL";
    /// File belongs to a module (directory).
    pub const PART_OF: &str = "PART_OF";
    /// File includes/imports another file (via #include or import statement).
    pub const INCLUDES: &str = "INCLUDES";
}

/// Check if a predicate string is a known predicate.
pub fn is_known_predicate(pred: &str) -> bool {
    matches!(
        pred,
        predicate::WAS_ASSOCIATED_WITH
            | predicate::USED
            | predicate::WAS_GENERATED_BY
            | predicate::WAS_INFORMED_BY
            | predicate::WAS_DERIVED_FROM
            | predicate::INFORMED_BY
            | predicate::BROADER
            | predicate::NARROWER
            | predicate::SUBJECT
            | predicate::RELATED
            | predicate::TYPE
            | predicate::CREATOR
            | predicate::DATE
            | predicate::DESCRIPTION
            | predicate::RDF_TYPE
            | predicate::BLOCKS
            | predicate::BLOCKED_BY
            | predicate::STATUS
            | predicate::ASSIGNED_TO
            | predicate::LINKED_INTENT
            | predicate::LINKED_GOAL
            | predicate::REFERENCES
            | predicate::APPLIES_TO
            | predicate::HAS_LABEL
            | predicate::PRIORITY
            | predicate::HAD_PLAN
            | predicate::HAD_MEMBER
            | predicate::GENERATED
            | predicate::EXPLAINED_BY
            | predicate::HAS_TODO
    )
}

/// List all known predicates.
pub fn all_predicates() -> Vec<&'static str> {
    vec![
        predicate::WAS_ASSOCIATED_WITH,
        predicate::USED,
        predicate::WAS_GENERATED_BY,
        predicate::WAS_INFORMED_BY,
        predicate::WAS_DERIVED_FROM,
        predicate::INFORMED_BY,
        predicate::BROADER,
        predicate::NARROWER,
        predicate::SUBJECT,
        predicate::RELATED,
        predicate::TYPE,
        predicate::CREATOR,
        predicate::DATE,
        predicate::DESCRIPTION,
        predicate::RDF_TYPE,
        predicate::BLOCKS,
        predicate::BLOCKED_BY,
        predicate::STATUS,
        predicate::ASSIGNED_TO,
        predicate::LINKED_INTENT,
        predicate::LINKED_GOAL,
        predicate::REFERENCES,
        predicate::APPLIES_TO,
        predicate::HAS_LABEL,
        predicate::PRIORITY,
        predicate::HAD_PLAN,
        predicate::HAD_MEMBER,
        predicate::GENERATED,
        predicate::EXPLAINED_BY,
        predicate::HAS_TODO,
    ]
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn all_predicates_are_known() {
        for pred in all_predicates() {
            assert!(
                is_known_predicate(pred),
                "Predicate '{}' not recognized",
                pred
            );
        }
    }

    #[test]
    fn predicate_count() {
        assert_eq!(all_predicates().len(), 30);
    }

    #[test]
    fn session_ledger_terms_registered() {
        // The ledger taxonomy vocabulary: session/turn typing plus the
        // execution and explanation relations.
        for pred in [
            predicate::HAD_PLAN,
            predicate::HAD_MEMBER,
            predicate::GENERATED,
            predicate::EXPLAINED_BY,
            predicate::HAS_TODO,
        ] {
            assert!(is_known_predicate(pred));
        }
        for ty in [
            entity_type::SESSION,
            entity_type::SESSION_TURN,
            entity_type::TODO,
            entity_type::PROVENANCE,
        ] {
            assert!(ty.starts_with("vault:"));
        }
    }

    #[test]
    fn predicates_have_prefix() {
        for pred in all_predicates() {
            assert!(pred.contains(':'), "Predicate '{}' missing prefix", pred);
        }
    }

    #[test]
    fn unknown_predicate_rejected() {
        assert!(!is_known_predicate("foo:bar"));
        assert!(!is_known_predicate(""));
    }

    #[test]
    fn edge_kinds_are_uppercase() {
        // Convention: edge kinds are SCREAMING_SNAKE_CASE
        let kinds = [
            edge_kind::MODIFIES,
            edge_kind::DEFINES,
            edge_kind::DEPENDS_ON,
            edge_kind::ON_VIEW,
            edge_kind::CHILD_OF,
            edge_kind::VISIBLE_FROM,
            edge_kind::CALLS,
            edge_kind::IMPORTS,
            edge_kind::EXPORTS,
            edge_kind::REFERENCES,
            edge_kind::LINKED_INTENT,
            edge_kind::LINKED_GOAL,
            edge_kind::ASSIGNED_TO,
            edge_kind::BLOCKS,
            edge_kind::BLOCKED_BY,
            edge_kind::AUTHORED_BY,
            edge_kind::HAS_LABEL,
            edge_kind::PART_OF,
            edge_kind::INCLUDES,
        ];
        for kind in &kinds {
            assert_eq!(
                *kind,
                kind.to_uppercase(),
                "Edge kind '{}' should be uppercase",
                kind
            );
        }
    }
}
