//! Transcript parsing, reasoning summaries, and unhashed storage.
//!
//! This module handles everything that goes into `change.unhashed["agent_turn"]`:
//!
//! 1. **Condensed transcript** — the raw conversation parsed into structured entries
//! 2. **AI-generated reasoning** — intent, outcome, learnings, friction, open items
//! 3. **Graph anchoring** — CRDT references that keep learnings attached to code as it evolves
//! 4. **Reasoning generation** — `ReasoningGenerator` trait + `ClaudeCliGenerator` implementation
//! 5. **Storage** — attach/extract/strip operations on `Change.unhashed`
//!
//! # Data Flow
//!
//! ```text
//! Agent transcript (JSONL/JSON)
//!     │
//!     ▼
//! condense_transcript()          → Vec<CondensedEntry>
//!     │
//!     ▼
//! format_condensed()             → human-readable text
//!     │
//!     ▼
//! ReasoningGenerator::generate() → TurnReasoning { intent, outcome, learnings, ... }
//!     │
//!     ▼
//! anchor_to_graph()              → CodeLearning._anchor populated from FileOps
//!     │
//!     ▼
//! UnhashedTurnData               → serialized into change.unhashed["agent_turn"]
//! ```
//!
//! # Example
//!
//! ```rust
//! use atomic_agent::transcript::{
//!     CondensedEntry, EntryType, TurnReasoning, Learnings, CodeLearning,
//!     UnhashedTurnData, ToolUseSummary,
//! };
//!
//! // Build condensed transcript entries
//! let entries = vec![
//!     CondensedEntry::user("Fix the auth bug in login.rs"),
//!     CondensedEntry::assistant("I'll fix the token validation..."),
//!     CondensedEntry::tool("Edit", Some("src/auth/login.rs")),
//!     CondensedEntry::tool("Bash", Some("cargo test")),
//!     CondensedEntry::assistant("The fix is applied and tests pass."),
//! ];
//!
//! // Build reasoning (normally generated by LLM)
//! let reasoning = TurnReasoning {
//!     intent: "Fix authentication bug preventing user login".into(),
//!     outcome: "Fixed token validation, all tests passing".into(),
//!     learnings: Learnings {
//!         repo: vec!["Auth module uses JWT with RS256, not HS256".into()],
//!         code: vec![CodeLearning::new(
//!             "src/auth/login.rs",
//!             Some(42),
//!             "Token expiry compared with wrong timezone",
//!         )],
//!         workflow: vec!["cargo test --lib is faster for auth changes".into()],
//!     },
//!     friction: vec!["3 layers of middleware to find the validation".into()],
//!     open_items: vec!["Refresh endpoint has the same bug".into()],
//! };
//!
//! // Package into unhashed turn data
//! let data = UnhashedTurnData {
//!     session_id: "sess-123".into(),
//!     turn_number: 3,
//!     transcript_format: "jsonl".into(),
//!     condensed_transcript: entries,
//!     condensed_text: "...".into(),
//!     prompts: vec!["Fix the auth bug in login.rs".into()],
//!     tools_used: vec![
//!         ToolUseSummary::new("Edit", 1, vec!["src/auth/login.rs".into()]),
//!     ],
//!     reasoning: Some(reasoning),
//!     redacted: false,
//! };
//!
//! assert_eq!(data.turn_number, 3);
//! assert!(data.reasoning.is_some());
//! ```

mod condense;
mod generator;
pub(crate) mod opencode;
mod reasoning;
mod storage;
mod types;

#[cfg(test)]
mod tests;

// Re-export all public types and functions
pub use condense::{
    aggregate_tool_usage, condense_claude_transcript, condense_opencode_transcript,
    condense_transcript, extract_prompts, format_condensed, format_for_agent, last_assistant_text,
};
pub use generator::{
    generate_reasoning, truncate_for_display, try_generate_reasoning, ClaudeCliGenerator,
    ReasoningGenerator,
};
pub use reasoning::{anchor_to_graph, CodeLearning, GraphAnchor, Learnings, TurnReasoning};
pub use storage::{
    attach_unhashed, extract_unhashed, has_unhashed, is_redacted, strip_unhashed, UnhashedTurnData,
    UNHASHED_KEY,
};
pub use types::{CondensedEntry, EntryType, ToolUseSummary};

#[cfg(test)]
pub use generator::MockGenerator;
