use std::fmt;

use serde::{Deserialize, Serialize};

// AI-Generated Reasoning Summary

/// AI-generated reasoning summary for a turn.
///
/// Captures what the agent learned during a turn — intent, outcome,
/// discoveries, problems, and deferred work. Generated by an LLM
/// (Claude CLI by default) from the condensed transcript.
///
/// Developers see learnings in terms of files, functions, and lines.
/// Under the hood, `anchor_to_graph()` attaches invisible CRDT references
/// so learnings automatically follow the code through renames and refactors.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct TurnReasoning {
    /// What the user was trying to accomplish (1-2 sentences).
    pub intent: String,

    /// What was actually achieved (1-2 sentences).
    pub outcome: String,

    /// Categorized discoveries made during the turn.
    pub learnings: Learnings,

    /// Problems, blockers, or annoyances encountered.
    #[serde(default)]
    pub friction: Vec<String>,

    /// Tech debt, unfinished work, or things to revisit later.
    #[serde(default)]
    pub open_items: Vec<String>,
}

impl TurnReasoning {
    /// Returns true if the reasoning has any code-specific learnings.
    pub fn has_code_learnings(&self) -> bool {
        !self.learnings.code.is_empty()
    }

    /// Returns the total number of learnings across all categories.
    pub fn learning_count(&self) -> usize {
        self.learnings.repo.len() + self.learnings.code.len() + self.learnings.workflow.len()
    }

    /// Returns true if the reasoning is essentially empty (no useful content).
    pub fn is_empty(&self) -> bool {
        self.intent.is_empty()
            && self.outcome.is_empty()
            && self.learnings.repo.is_empty()
            && self.learnings.code.is_empty()
            && self.learnings.workflow.is_empty()
            && self.friction.is_empty()
            && self.open_items.is_empty()
    }
}

impl fmt::Display for TurnReasoning {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        writeln!(f, "Intent: {}", self.intent)?;
        writeln!(f, "Outcome: {}", self.outcome)?;
        if !self.learnings.repo.is_empty() {
            writeln!(f, "Repo learnings:")?;
            for l in &self.learnings.repo {
                writeln!(f, "  • {}", l)?;
            }
        }
        if !self.learnings.code.is_empty() {
            writeln!(f, "Code learnings:")?;
            for l in &self.learnings.code {
                writeln!(f, "  • {}", l)?;
            }
        }
        if !self.learnings.workflow.is_empty() {
            writeln!(f, "Workflow learnings:")?;
            for l in &self.learnings.workflow {
                writeln!(f, "  • {}", l)?;
            }
        }
        if !self.friction.is_empty() {
            writeln!(f, "Friction:")?;
            for fr in &self.friction {
                writeln!(f, "  • {}", fr)?;
            }
        }
        if !self.open_items.is_empty() {
            writeln!(f, "Open items:")?;
            for item in &self.open_items {
                writeln!(f, "  • {}", item)?;
            }
        }
        Ok(())
    }
}

/// Categorized learnings from a turn.
#[derive(Clone, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct Learnings {
    /// Codebase-specific patterns, conventions, or gotchas.
    ///
    /// Examples:
    /// - "Auth module uses JWT with RS256, not HS256"
    /// - "Database migrations are in migrations/ not db/"
    #[serde(default)]
    pub repo: Vec<String>,

    /// Findings about specific code locations.
    ///
    /// Each learning is tied to a file (and optionally function/line).
    /// The `_anchor` field (when populated) keeps the learning attached
    /// to the code as it moves through renames and refactors.
    #[serde(default)]
    pub code: Vec<CodeLearning>,

    /// General development practices or tool usage insights.
    ///
    /// Examples:
    /// - "cargo test --lib is faster for auth changes"
    /// - "Dev server needs restart after config.toml changes"
    #[serde(default)]
    pub workflow: Vec<String>,
}

impl Learnings {
    /// Returns the total number of learnings across all categories.
    pub fn total(&self) -> usize {
        self.repo.len() + self.code.len() + self.workflow.len()
    }

    /// Returns true if there are no learnings in any category.
    pub fn is_empty(&self) -> bool {
        self.repo.is_empty() && self.code.is_empty() && self.workflow.is_empty()
    }
}

/// A learning tied to a specific code location.
///
/// # User-Facing Fields
///
/// Developers see: file path, line number, function name, and the finding
/// in plain language. These are what appears in `atomic log --learnings`
/// and in the server UI.
///
/// # Graph Anchor (Invisible)
///
/// The `_anchor` field contains CRDT references (TrunkId, BranchId, LeafId)
/// that keep the learning attached to the specific tokens in the graph.
/// This is populated by `anchor_to_graph()` after recording and is never
/// shown in CLI output. The server uses it to resolve the learning to the
/// current file/line position even after renames and refactors.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct CodeLearning {
    /// File path (e.g., `"src/auth/login.rs"`).
    pub path: String,

    /// Line number at recording time.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub line: Option<u32>,

    /// End line for multi-line ranges.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub end_line: Option<u32>,

    /// Function or method name, if identifiable.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub function: Option<String>,

    /// What was learned, in plain language.
    pub finding: String,

    /// Category of the finding.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub category: Option<String>,

    /// CRDT graph anchor — invisible to users, used by server for tracking.
    ///
    /// Populated by `anchor_to_graph()` from the change's `FileOps`.
    /// Contains TrunkId (file), BranchId (lines), LeafId (tokens) that
    /// keep this learning attached to the code as it moves.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub _anchor: Option<GraphAnchor>,
}

impl CodeLearning {
    /// Create a new code learning with the minimum required fields.
    pub fn new(path: impl Into<String>, line: Option<u32>, finding: impl Into<String>) -> Self {
        Self {
            path: path.into(),
            line,
            end_line: None,
            function: None,
            finding: finding.into(),
            category: None,
            _anchor: None,
        }
    }

    /// Set the function name.
    #[must_use]
    pub fn with_function(mut self, function: impl Into<String>) -> Self {
        self.function = Some(function.into());
        self
    }

    /// Set the end line for a range.
    #[must_use]
    pub fn with_end_line(mut self, end_line: u32) -> Self {
        self.end_line = Some(end_line);
        self
    }

    /// Set the category.
    #[must_use]
    pub fn with_category(mut self, category: impl Into<String>) -> Self {
        self.category = Some(category.into());
        self
    }

    /// Returns true if this learning has a graph anchor.
    pub fn is_anchored(&self) -> bool {
        self._anchor.is_some()
    }
}

impl fmt::Display for CodeLearning {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.path)?;
        if let Some(line) = self.line {
            write!(f, ":{}", line)?;
            if let Some(end) = self.end_line {
                write!(f, "-{}", end)?;
            }
        }
        if let Some(ref func) = self.function {
            write!(f, " ({})", func)?;
        }
        write!(f, " — {}", self.finding)?;
        if let Some(ref cat) = self.category {
            write!(f, " [{}]", cat)?;
        }
        Ok(())
    }
}

// Graph Anchor (invisible to users)

/// CRDT graph references that keep a learning anchored to specific code.
///
/// This is populated from the change's `FileOps` by `anchor_to_graph()`.
/// The server resolves these IDs to current file/line positions when
/// displaying learnings. Users never see this — they see files and lines.
///
/// If the referenced code is renamed or moved, the TrunkId/BranchId/LeafId
/// still resolve correctly because they're part of the graph, not computed
/// from file position.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct GraphAnchor {
    /// TrunkId as (change_id, file_idx) — the file, survives renames.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub trunk: Option<(u64, u32)>,

    /// BranchIds as (change_id, branch_idx) — the lines, survive insertions.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub branches: Vec<(u64, u32)>,

    /// LeafIds as (change_id, leaf_idx) — the tokens, survive refactors.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub leaves: Vec<(u64, u32)>,
}

impl GraphAnchor {
    /// Create an empty anchor.
    pub fn empty() -> Self {
        Self {
            trunk: None,
            branches: Vec::new(),
            leaves: Vec::new(),
        }
    }

    /// Returns true if this anchor has any references.
    pub fn is_populated(&self) -> bool {
        self.trunk.is_some() || !self.branches.is_empty() || !self.leaves.is_empty()
    }
}

/// Anchor code learnings to the CRDT graph using FileOps from the recorded change.
///
/// This is a post-processing step called after the LLM returns human-readable
/// findings. For each `CodeLearning`, it looks up the file path and line number
/// in the change's `FileOps` to find the corresponding TrunkId, BranchId, and
/// LeafId references.
///
/// # Arguments
///
/// * `learnings` — The code learnings to anchor (modified in place)
/// * `file_ops` — The CRDT operations from the recorded change
///
/// # Behavior
///
/// - If a learning's `path` matches a `FileOps.path()`, the `trunk` is set
/// - If a learning's `line` matches a `LineOps` line number, `branches` are set
/// - `leaves` are populated from the `LeafOp`s of matched lines
/// - If no match is found, the anchor is left as `None` (the learning still
///   works, just without auto-tracking through renames/refactors)
pub fn anchor_to_graph(learnings: &mut [CodeLearning], file_ops: &[atomic_core::change::FileOps]) {
    for learning in learnings.iter_mut() {
        let mut anchor = GraphAnchor::empty();

        // Find the matching file in FileOps
        for fop in file_ops {
            if fop.path() != learning.path {
                continue;
            }

            // Set trunk anchor (file level)
            let tid = fop.trunk_id();
            anchor.trunk = Some((tid.change_id().get(), tid.file_idx()));

            // If we have a line number, try to match line operations
            if let Some(target_line) = learning.line {
                for line_op in fop.line_ops() {
                    // Check both old and new line numbers — deletes have old,
                    // inserts have new, some ops have both
                    let op_line = line_op.new_line_num().or_else(|| line_op.old_line_num());
                    let matches = match (op_line, learning.end_line) {
                        (Some(l), Some(end)) => l as u32 >= target_line && (l as u32) <= end,
                        (Some(l), None) => l as u32 == target_line,
                        (None, _) => false,
                    };

                    if matches {
                        let bid = line_op.branch_id();
                        anchor
                            .branches
                            .push((bid.change_id().get(), bid.branch_idx()));

                        // Collect leaf IDs from the line's operations
                        for leaf_op in line_op.leaf_ops() {
                            if let Some(lid) = leaf_op_id(leaf_op) {
                                anchor.leaves.push(lid);
                            }
                        }
                    }
                }
            }

            break; // Found the file, done
        }

        if anchor.is_populated() {
            learning._anchor = Some(anchor);
        }
    }
}

// CRDT Anchor Helpers

/// Extract the (change_id, leaf_idx) tuple from a LeafOp, if it references an existing leaf.
///
/// Insert ops don't carry an assigned LeafId (the ID is assigned during apply),
/// so they return None. Delete, Replace, and Restore reference existing leaves.
fn leaf_op_id(op: &atomic_core::crdt::LeafOp) -> Option<(u64, u32)> {
    op.leaf_id()
        .map(|lid| (lid.change_id().get(), lid.leaf_idx()))
}
